<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CustomizedPenghargaanTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('penghargaan')->delete();
        
        \DB::table('penghargaan')->insert(array (
            0 => 
            array (
                'id' => 1,
                'parent_id' => NULL,
                'simpeg_id' => '1-',
                'name' => 'BINTANG REPUBLIK INDONESIA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'parent_id' => NULL,
                'simpeg_id' => '10-',
                'name' => 'BINTANG SEWINDU ANGKATAN PERANG RI',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => 'Kalian Luar Biasa',
                'order' => 1,
            ),
            2 => 
            array (
                'id' => 4,
                'parent_id' => NULL,
                'simpeg_id' => '11-',
                'name' => 'SATYALANCANA BHAKTI',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            3 => 
            array (
                'id' => 6,
                'parent_id' => NULL,
                'simpeg_id' => '12-',
                'name' => 'SATYALANCANA TELADAN',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            4 => 
            array (
                'id' => 8,
                'parent_id' => NULL,
                'simpeg_id' => '13-',
                'name' => 'SATYALANCANA KESETIAAN',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            5 => 
            array (
                'id' => 13,
                'parent_id' => NULL,
                'simpeg_id' => '14-',
                'name' => 'SATYALANCANA PERANG KEMERDEKAAN',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            6 => 
            array (
                'id' => 17,
                'parent_id' => NULL,
                'simpeg_id' => '15-',
                'name' => 'SATYALANCANA SAPTAMARGA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            7 => 
            array (
                'id' => 18,
                'parent_id' => NULL,
                'simpeg_id' => '16-',
                'name' => 'SATYALANCANA GOM',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            8 => 
            array (
                'id' => 28,
                'parent_id' => NULL,
                'simpeg_id' => '17-',
                'name' => 'SATYALANCANA PERINTIS PERGERAKAN KEMERDEKAAN',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            9 => 
            array (
                'id' => 29,
                'parent_id' => NULL,
                'simpeg_id' => '18-',
                'name' => 'SATYALANCANA PERINGATAN PERJUANGAN KEMERDEKAAN',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            10 => 
            array (
                'id' => 30,
                'parent_id' => NULL,
                'simpeg_id' => '19-',
                'name' => 'SATYALANCANA PEMBANGUNAN',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            11 => 
            array (
                'id' => 31,
                'parent_id' => NULL,
                'simpeg_id' => '2-',
                'name' => 'BINTANG MAHAPUTERA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            12 => 
            array (
                'id' => 32,
                'parent_id' => NULL,
                'simpeg_id' => '20-',
                'name' => 'SATYALANCANA KARYA SATYA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            13 => 
            array (
                'id' => 42,
                'parent_id' => NULL,
                'simpeg_id' => '21-',
                'name' => 'SATYALANCANA KEBAKTIAN SOSIAL',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            14 => 
            array (
                'id' => 44,
                'parent_id' => NULL,
                'simpeg_id' => '22-',
                'name' => 'SATYALANCANA KEBUDAYAAN',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            15 => 
            array (
                'id' => 46,
                'parent_id' => NULL,
                'simpeg_id' => '23-',
                'name' => 'SATYALANCANA JASA DHARMA ANGKATAN LAUT',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            16 => 
            array (
                'id' => 48,
                'parent_id' => NULL,
                'simpeg_id' => '24-',
                'name' => 'SATYALANCANA SATYA DASA WARSA POLRI',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            17 => 
            array (
                'id' => 50,
                'parent_id' => NULL,
                'simpeg_id' => '25-',
                'name' => 'SATYALANCANA JANA UTAMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            18 => 
            array (
                'id' => 51,
                'parent_id' => NULL,
                'simpeg_id' => '26-',
                'name' => 'SATYALANCANA KSATRYA TAMTAMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            19 => 
            array (
                'id' => 52,
                'parent_id' => NULL,
                'simpeg_id' => '27-',
                'name' => 'SATYALANCANA KARYA BHAKTI',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            20 => 
            array (
                'id' => 53,
                'parent_id' => NULL,
                'simpeg_id' => '28-',
                'name' => 'SATYALANCANA PRASETYA PANCA WARSA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            21 => 
            array (
                'id' => 54,
                'parent_id' => NULL,
                'simpeg_id' => '29-',
                'name' => 'SATYALANCANA KEAMANAN',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            22 => 
            array (
                'id' => 55,
                'parent_id' => NULL,
                'simpeg_id' => '3-',
                'name' => 'BINTANG JASA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            23 => 
            array (
                'id' => 56,
                'parent_id' => NULL,
                'simpeg_id' => '30-',
                'name' => 'SATYALANCANA WIRA KARYA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => 'hey',
                'order' => 1,
            ),
            24 => 
            array (
                'id' => 58,
                'parent_id' => NULL,
                'simpeg_id' => '31-',
                'name' => 'SATYALANCANA SATYA DHARMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            25 => 
            array (
                'id' => 60,
                'parent_id' => NULL,
                'simpeg_id' => '32-',
                'name' => 'SATYALANCANA WIRA DHARMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            26 => 
            array (
                'id' => 62,
                'parent_id' => NULL,
                'simpeg_id' => '33-',
                'name' => 'SATYALANCANA YUDHA UTAMA KKO-AL',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            27 => 
            array (
                'id' => 65,
                'parent_id' => NULL,
                'simpeg_id' => '34-',
                'name' => 'SATYALANCANA DWIYA SISTHA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            28 => 
            array (
                'id' => 66,
                'parent_id' => NULL,
                'simpeg_id' => '35-',
                'name' => 'SATYALANCANA PENEGAK',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            29 => 
            array (
                'id' => 67,
                'parent_id' => NULL,
                'simpeg_id' => '36-',
                'name' => 'SATYALANCANA PEPERA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            30 => 
            array (
                'id' => 68,
                'parent_id' => NULL,
                'simpeg_id' => '4-',
                'name' => 'BINTANG YUDHA DHARMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            31 => 
            array (
                'id' => 72,
                'parent_id' => NULL,
                'simpeg_id' => '5-',
                'name' => 'BINTANG KARTIKA EKA PAKSI',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            32 => 
            array (
                'id' => 74,
                'parent_id' => NULL,
                'simpeg_id' => '51-',
                'name' => 'PIAGAM SATYA KARYA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            33 => 
            array (
                'id' => 78,
                'parent_id' => NULL,
                'simpeg_id' => '52-',
                'name' => 'PIAGAM PENGHARGAAN ATAS JASA KHUSUS TEK.KEKARYAAN',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            34 => 
            array (
                'id' => 80,
                'parent_id' => NULL,
                'simpeg_id' => '53-',
                'name' => 'PIAGAM PENGHARGAAN TELADAN',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            35 => 
            array (
                'id' => 84,
                'parent_id' => NULL,
                'simpeg_id' => '54-',
                'name' => 'PIAGAM PENGHARGAAN ANUMERTA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            36 => 
            array (
                'id' => 85,
                'parent_id' => NULL,
                'simpeg_id' => '55-',
                'name' => 'PIAGAM PENGHARGAAN KHUSUS',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            37 => 
            array (
                'id' => 86,
                'parent_id' => NULL,
                'simpeg_id' => '6-',
                'name' => 'BINTANG JALASENA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            38 => 
            array (
                'id' => 87,
                'parent_id' => NULL,
                'simpeg_id' => '60-',
                'name' => 'SATYALANCANA SANTI DHARMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            39 => 
            array (
                'id' => 89,
                'parent_id' => NULL,
                'simpeg_id' => '61-',
                'name' => 'SATYALANCANA SEROJA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            40 => 
            array (
                'id' => 91,
                'parent_id' => NULL,
                'simpeg_id' => '62-',
                'name' => 'SATYALANCANA PENDIDIKAN',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            41 => 
            array (
                'id' => 5,
                'parent_id' => 1,
                'simpeg_id' => '1-2-',
                'name' => 'BINTANG REPUBLIK INDONESIA ADIPRADANA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            42 => 
            array (
                'id' => 7,
                'parent_id' => 1,
                'simpeg_id' => '1-3-',
                'name' => 'BINTANG REPUBLIK INDONESIA UTAMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            43 => 
            array (
                'id' => 9,
                'parent_id' => 8,
                'simpeg_id' => '13-1-',
                'name' => 'SATYALANCANA KESETIAAN  8 TAHUN',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            44 => 
            array (
                'id' => 10,
                'parent_id' => 8,
                'simpeg_id' => '13-2-',
                'name' => 'SATYALANCANA KESETIAAN 16 TAHUN',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            45 => 
            array (
                'id' => 11,
                'parent_id' => 8,
                'simpeg_id' => '13-3-',
                'name' => 'SATYALANCANA KESETIAAN 24 TAHUN',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            46 => 
            array (
                'id' => 12,
                'parent_id' => 1,
                'simpeg_id' => '1-4-',
                'name' => 'BINTANG REPUBLIK INDONESIA PRATAMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            47 => 
            array (
                'id' => 15,
                'parent_id' => 13,
                'simpeg_id' => '14-2-',
                'name' => 'SATYALANCANA PERANG KEMERDEKAAN KELAS II',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            48 => 
            array (
                'id' => 16,
                'parent_id' => 1,
                'simpeg_id' => '1-5-',
                'name' => 'BINTANG REPUBLIK INDONESIA NARARYA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            49 => 
            array (
                'id' => 19,
                'parent_id' => 18,
                'simpeg_id' => '16-1-',
                'name' => 'SATYALANCANA GOM KELAS I',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            50 => 
            array (
                'id' => 20,
                'parent_id' => 18,
                'simpeg_id' => '16-2-',
                'name' => 'SATYALANCANA GOM KELAS II',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            51 => 
            array (
                'id' => 21,
                'parent_id' => 18,
                'simpeg_id' => '16-3-',
                'name' => 'SATYALANCANA GOM KELAS III',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            52 => 
            array (
                'id' => 22,
                'parent_id' => 18,
                'simpeg_id' => '16-4-',
                'name' => 'SATYALANCANA GOM KELAS IV',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            53 => 
            array (
                'id' => 23,
                'parent_id' => 18,
                'simpeg_id' => '16-5-',
                'name' => 'SATYALANCANA GOM KELAS V',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            54 => 
            array (
                'id' => 24,
                'parent_id' => 18,
                'simpeg_id' => '16-6-',
                'name' => 'SATYALANCANA GOM KELAS VI',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            55 => 
            array (
                'id' => 25,
                'parent_id' => 18,
                'simpeg_id' => '16-7-',
                'name' => 'SATYALANCANA GOM KELAS VII',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            56 => 
            array (
                'id' => 26,
                'parent_id' => 18,
                'simpeg_id' => '16-8-',
                'name' => 'SATYALANCANA GOM KELAS VIII',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            57 => 
            array (
                'id' => 27,
                'parent_id' => 18,
                'simpeg_id' => '16-9-',
                'name' => 'SATYALANCANA GOM KELAS IX',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            58 => 
            array (
                'id' => 34,
                'parent_id' => 32,
                'simpeg_id' => '20-2-',
                'name' => 'SATYALANCANA KARYA SATYA KELAS II',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            59 => 
            array (
                'id' => 35,
                'parent_id' => 32,
                'simpeg_id' => '20-3-',
                'name' => 'SATYALANCANA KARYA SATYA KELAS III',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            60 => 
            array (
                'id' => 36,
                'parent_id' => 32,
                'simpeg_id' => '20-4-',
                'name' => 'SATYALANCANA KARYA SATYA KELAS IV',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            61 => 
            array (
                'id' => 37,
                'parent_id' => 32,
                'simpeg_id' => '20-5-',
                'name' => 'SATYALANCANA KARYA SATYA KELAS V',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            62 => 
            array (
                'id' => 38,
                'parent_id' => 32,
                'simpeg_id' => '20-6-',
                'name' => 'SATYALANCANA KARYA SATYA XXX TAHUN',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            63 => 
            array (
                'id' => 39,
                'parent_id' => 32,
                'simpeg_id' => '20-7-',
                'name' => 'SATYALANCANA KARYA SATYA XX TAHUN',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            64 => 
            array (
                'id' => 40,
                'parent_id' => 32,
                'simpeg_id' => '20-8-',
                'name' => 'SATYALANCANA KARYA SATYA X TAHUN',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            65 => 
            array (
                'id' => 41,
                'parent_id' => 31,
                'simpeg_id' => '2-1-',
                'name' => 'BINTANG MAHAPUTERA ADIPURNA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            66 => 
            array (
                'id' => 43,
                'parent_id' => 31,
                'simpeg_id' => '2-2-',
                'name' => 'BINTANG MAHAPUTERA ADIPRADANA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            67 => 
            array (
                'id' => 45,
                'parent_id' => 31,
                'simpeg_id' => '2-3-',
                'name' => 'BINTANG MAHAPUTERA UTAMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            68 => 
            array (
                'id' => 49,
                'parent_id' => 31,
                'simpeg_id' => '2-5-',
                'name' => 'BINTANG MAHAPUTERA NARARYA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            69 => 
            array (
                'id' => 57,
                'parent_id' => 55,
                'simpeg_id' => '3-1-',
                'name' => 'BINTANG JASA UTAMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            70 => 
            array (
                'id' => 59,
                'parent_id' => 55,
                'simpeg_id' => '3-2-',
                'name' => 'BINTANG JASA PRATAMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            71 => 
            array (
                'id' => 61,
                'parent_id' => 55,
                'simpeg_id' => '3-3-',
                'name' => 'BINTANG JASA NARARYA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            72 => 
            array (
                'id' => 63,
                'parent_id' => 62,
                'simpeg_id' => '33-1-',
                'name' => 'SATYALANCANA YUDHA UTAMA KKO-AL KELAS I',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            73 => 
            array (
                'id' => 64,
                'parent_id' => 62,
                'simpeg_id' => '33-2-',
                'name' => 'SATYALANCANA YUDHA UTAMA KKO-AL KELAS II',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            74 => 
            array (
                'id' => 69,
                'parent_id' => 68,
                'simpeg_id' => '4-1-',
                'name' => 'BINTANG YUDHA DHARMA UTAMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            75 => 
            array (
                'id' => 70,
                'parent_id' => 68,
                'simpeg_id' => '4-2-',
                'name' => 'BINTANG YUDHA DHARMA PRATAMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            76 => 
            array (
                'id' => 71,
                'parent_id' => 68,
                'simpeg_id' => '4-3-',
                'name' => 'BINTANG YUDHA DHARMA NARARYA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            77 => 
            array (
                'id' => 75,
                'parent_id' => 74,
                'simpeg_id' => '51-1-',
                'name' => 'PIAGAM SATYA KARYA 20 TAHUN',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            78 => 
            array (
                'id' => 76,
                'parent_id' => 74,
                'simpeg_id' => '51-2-',
                'name' => 'PIAGAM SATYA KARYA 30 TAHUN',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            79 => 
            array (
                'id' => 77,
                'parent_id' => 72,
                'simpeg_id' => '5-2-',
                'name' => 'BINTANG KARTIKA EKA PAKSI PRATAMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            80 => 
            array (
                'id' => 79,
                'parent_id' => 72,
                'simpeg_id' => '5-3-',
                'name' => 'BINTANG KARTIKA EKA PAKSI NARARYA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            81 => 
            array (
                'id' => 81,
                'parent_id' => 80,
                'simpeg_id' => '53-1-',
                'name' => 'PIAGAM PENGHARGAAN TELADAN KEPEMIMPINAN',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            82 => 
            array (
                'id' => 82,
                'parent_id' => 80,
                'simpeg_id' => '53-2-',
                'name' => 'PIAGAM PENGHARGAAN TELADAN KEPEGAWAIAN',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            83 => 
            array (
                'id' => 83,
                'parent_id' => 80,
                'simpeg_id' => '53-3-',
                'name' => 'PIAGAM PENGHARGAAN TELADAN PELAK. TUGAS',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            84 => 
            array (
                'id' => 88,
                'parent_id' => 86,
                'simpeg_id' => '6-1-',
                'name' => 'BINTANG JALASENA UTAMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            85 => 
            array (
                'id' => 90,
                'parent_id' => 86,
                'simpeg_id' => '6-2-',
                'name' => 'BINTANG JALASENA PRATAMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            86 => 
            array (
                'id' => 93,
                'parent_id' => NULL,
                'simpeg_id' => '63-',
                'name' => 'NUGRAHA SAKANTI JANA UTAMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            87 => 
            array (
                'id' => 94,
                'parent_id' => NULL,
                'simpeg_id' => '64-',
                'name' => 'NUGRAHA SAKANTI KSATRYA TAMTAMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            88 => 
            array (
                'id' => 95,
                'parent_id' => NULL,
                'simpeg_id' => '65-',
                'name' => 'NUGRAHA SAKANTI KARYA BHAKTI',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            89 => 
            array (
                'id' => 96,
                'parent_id' => NULL,
                'simpeg_id' => '66-',
                'name' => 'SAM KARYA NUGRAHA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            90 => 
            array (
                'id' => 97,
                'parent_id' => NULL,
                'simpeg_id' => '67-',
                'name' => 'PRASAMYA PURNAKARYA NUGRAHA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            91 => 
            array (
                'id' => 98,
                'parent_id' => NULL,
                'simpeg_id' => '68-',
                'name' => 'BINTANG SAKTI',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            92 => 
            array (
                'id' => 99,
                'parent_id' => NULL,
                'simpeg_id' => '69-',
                'name' => 'BINTANG DHARMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            93 => 
            array (
                'id' => 100,
                'parent_id' => NULL,
                'simpeg_id' => '7-',
                'name' => 'BINTANG SWA BHUWANA PAKSA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            94 => 
            array (
                'id' => 101,
                'parent_id' => NULL,
                'simpeg_id' => '70-',
                'name' => 'BINTANG GERILYA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            95 => 
            array (
                'id' => 103,
                'parent_id' => NULL,
                'simpeg_id' => '71-',
                'name' => 'BINTANG BUDAYA PARAMA DHARMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            96 => 
            array (
                'id' => 105,
                'parent_id' => NULL,
                'simpeg_id' => '72-',
                'name' => 'SATYALANCANA PERISTIWA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            97 => 
            array (
                'id' => 108,
                'parent_id' => NULL,
                'simpeg_id' => '73-1-',
                'name' => 'tes lagi',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => 'tes lagi',
                'order' => 1,
            ),
            98 => 
            array (
                'id' => 109,
                'parent_id' => NULL,
                'simpeg_id' => '74-',
                'name' => 'BEST ASN OF THE YEAR',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => 'Pegawai Terbaik Tahun Ini',
                'order' => 1,
            ),
            99 => 
            array (
                'id' => 110,
                'parent_id' => NULL,
                'simpeg_id' => '75-1-',
                'name' => 'Penghargaan Baru II',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => 'baru II',
                'order' => 1,
            ),
            100 => 
            array (
                'id' => 111,
                'parent_id' => NULL,
                'simpeg_id' => '76-',
                'name' => 'ARSIPARIS TELADAN',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => 'JUARA I',
                'order' => 1,
            ),
            101 => 
            array (
                'id' => 112,
                'parent_id' => NULL,
                'simpeg_id' => '77-',
                'name' => 'PRESTASI TERBAIK KE II LATSAR CPNS GOL II TAHUN 2022',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => 'PRESTASI TERBAI II',
                'order' => 1,
            ),
            102 => 
            array (
                'id' => 113,
                'parent_id' => NULL,
                'simpeg_id' => '8-',
                'name' => 'BINTANG BHAYANGKARA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            103 => 
            array (
                'id' => 117,
                'parent_id' => NULL,
                'simpeg_id' => '9-',
                'name' => 'BINTANG GARUDA X',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => 'Bintang Garuda',
                'order' => 1,
            ),
            104 => 
            array (
                'id' => 3,
                'parent_id' => 1,
                'simpeg_id' => '1-1-',
                'name' => 'BINTANG REPUBLIK INDONESIA ADIPURNA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            105 => 
            array (
                'id' => 14,
                'parent_id' => 13,
                'simpeg_id' => '14-1-',
                'name' => 'SATYALANCANA PERANG KEMERDEKAAN KELAS I',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            106 => 
            array (
                'id' => 33,
                'parent_id' => 32,
                'simpeg_id' => '20-1-',
                'name' => 'SATYALANCANA KARYA SATYA KELAS I',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            107 => 
            array (
                'id' => 47,
                'parent_id' => 31,
                'simpeg_id' => '2-4-',
                'name' => 'BINTANG MAHAPUTERA PRATAMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            108 => 
            array (
                'id' => 73,
                'parent_id' => 72,
                'simpeg_id' => '5-1-',
                'name' => 'BINTANG KARTIKA EKA PAKSI UTAMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            109 => 
            array (
                'id' => 92,
                'parent_id' => 86,
                'simpeg_id' => '6-3-',
                'name' => 'BINTANG JALASENA NARARYA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            110 => 
            array (
                'id' => 102,
                'parent_id' => 100,
                'simpeg_id' => '7-1-',
                'name' => 'BINTANG SWA BHUWANA PAKSA UTAMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            111 => 
            array (
                'id' => 104,
                'parent_id' => 100,
                'simpeg_id' => '7-2-',
                'name' => 'BINTANG SWA BHUWANA PAKSA PRATAMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            112 => 
            array (
                'id' => 106,
                'parent_id' => 105,
                'simpeg_id' => '72-1-',
                'name' => 'LAIN-LAIN',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            113 => 
            array (
                'id' => 107,
                'parent_id' => 100,
                'simpeg_id' => '7-3-',
                'name' => 'BINTANG SWA BHUWANA PAKSA NARARYA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            114 => 
            array (
                'id' => 114,
                'parent_id' => 113,
                'simpeg_id' => '8-1-',
                'name' => 'BINTANG BHAYANGKARA UTAMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            115 => 
            array (
                'id' => 115,
                'parent_id' => 113,
                'simpeg_id' => '8-2-',
                'name' => 'BINTANG BHAYANGKARA PRATAMA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
            116 => 
            array (
                'id' => 116,
                'parent_id' => 113,
                'simpeg_id' => '8-3-',
                'name' => 'BINTANG BHAYANGKARA NARARYA',
                'created_at' => '2023-07-18 01:43:58',
                'updated_at' => '2023-07-18 01:43:58',
                'keterangan' => NULL,
                'order' => 1,
            ),
        ));
        
        
    }
}