<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CustomizedPejabatPenetapTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pejabat_penetap')->delete();
        
        \DB::table('pejabat_penetap')->insert(array (
            0 => 
            array (
                'id' => 1049,
                'nama' => 'Dr. H. Noerhadi Magetsari',
                'nip' => '130 197 928',
                'golongan' => 'IV/e ',
                'pangkat' => 'Pembina Utama ',
                'tahun_awal' => 1990,
                'tahun_akhir' => 2003,
                'satker_id' => '01',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Kepala ANRI',
            ),
            1 => 
            array (
                'id' => 1051,
                'nama' => 'Rita Yunieti, S,SH',
                'nip' => '19700607 199703 2 001',
                'golongan' => 'IV/b',
                'pangkat' => 'Pembina Tk. I',
                'tahun_awal' => 2015,
                'tahun_akhir' => 2017,
                'satker_id' => '01010202',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Kepala Bagian Kepegawaian',
            ),
            2 => 
            array (
                'id' => 1052,
                'nama' => 'Drs. Amieka Hasraf, MM',
                'nip' => '19660729 199403 1 001',
                'golongan' => 'IV/c',
                'pangkat' => 'Pembina Utama Muda',
                'tahun_awal' => 2012,
                'tahun_akhir' => 2015,
                'satker_id' => '01010202',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Kepala Bagian Kepegawaian',
            ),
            3 => 
            array (
                'id' => 1053,
                'nama' => 'Drs.AA. Gede Sumardika',
                'nip' => '19670515 199403 1 01',
                'golongan' => 'IV/a',
                'pangkat' => 'Pembina, ',
                'tahun_awal' => 2009,
                'tahun_akhir' => 2012,
                'satker_id' => '01010202',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Kepala Bagian Kepegawaian',
            ),
            4 => 
            array (
                'id' => 1054,
                'nama' => 'Dra. Sulistyowati',
                'nip' => '19650215 199303 2 001',
                'golongan' => 'IV.a',
                'pangkat' => 'Pembina',
                'tahun_awal' => 2005,
                'tahun_akhir' => 2010,
                'satker_id' => '01010202',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Kepala Bagian Kepegawaian',
            ),
            5 => 
            array (
                'id' => 1055,
                'nama' => 'Desti Trisfati Dwi Putri, SAP, M.AP ',
                'nip' => '197812262000032001',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk. I',
                'tahun_awal' => 2019,
                'tahun_akhir' => 2022,
                'satker_id' => '01010202',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Kepala Bagian Kepegawaian',
            ),
            6 => 
            array (
                'id' => 2055,
                'nama' => 'Dra. Prihatni Wuryatmini',
                'nip' => '196801091994032001',
                'golongan' => 'IV/b',
                'pangkat' => 'Pembina Tk I',
                'tahun_awal' => 2018,
                'tahun_akhir' => 2019,
                'satker_id' => '01010202',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Kepala Bagian Kepegawaian',
            ),
            7 => 
            array (
                'id' => 2056,
                'nama' => 'Dr.Mustari Irawan, M.P.A',
                'nip' => '195906211987031001',
                'golongan' => 'IV/e ',
                'pangkat' => 'Pembina Utama ',
                'tahun_awal' => 2013,
                'tahun_akhir' => 2019,
                'satker_id' => '01',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Kepala ANRI',
            ),
            8 => 
            array (
                'id' => 2,
                'nama' => 'Dr. H. Alfitra Salamm, APU ',
                'nip' => '19850630 200912 1 ',
                'golongan' => NULL,
                'pangkat' => NULL,
                'tahun_awal' => NULL,
                'tahun_akhir' => NULL,
                'satker_id' => NULL,
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Sekretaris Kementerian',
            ),
            9 => 
            array (
                'id' => 3,
                'nama' => 'Ir. H. Joko Widodo',
                'nip' => ' ',
                'golongan' => NULL,
                'pangkat' => NULL,
                'tahun_awal' => NULL,
                'tahun_akhir' => NULL,
                'satker_id' => NULL,
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Presiden Republik Indonesia',
            ),
            10 => 
            array (
                'id' => 4,
                'nama' => 'Imam Nahrawi',
                'nip' => ' ',
                'golongan' => NULL,
                'pangkat' => NULL,
                'tahun_awal' => NULL,
                'tahun_akhir' => NULL,
                'satker_id' => NULL,
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Menteri Pemuda dan Olahraga',
            ),
            11 => 
            array (
                'id' => 5,
                'nama' => 'Edi Suryanto, S.IP.,M.SI',
                'nip' => '196511031985031001',
                'golongan' => NULL,
                'pangkat' => NULL,
                'tahun_awal' => NULL,
                'tahun_akhir' => NULL,
                'satker_id' => NULL,
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Bagian Kepegawaian',
            ),
            12 => 
            array (
                'id' => 6,
                'nama' => 'Deden Dendi, S.Sos',
                'nip' => '197402212000031001',
                'golongan' => NULL,
                'pangkat' => NULL,
                'tahun_awal' => NULL,
                'tahun_akhir' => NULL,
                'satker_id' => NULL,
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Sub Bag Mutasi Dan Kepangkatan Pegawai',
            ),
            13 => 
            array (
                'id' => 7,
                'nama' => 'BIMA HARIA WIBISANA',
                'nip' => ' ',
                'golongan' => NULL,
                'pangkat' => NULL,
                'tahun_awal' => NULL,
                'tahun_akhir' => NULL,
                'satker_id' => NULL,
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Kepala Badan Kepegawaian Negara',
            ),
            14 => 
            array (
                'id' => 8,
                'nama' => 'Drs.. Gatot Sulistiantoro Dewa Broto, M.B.A',
                'nip' => '196110311989031002',
                'golongan' => NULL,
                'pangkat' => NULL,
                'tahun_awal' => NULL,
                'tahun_akhir' => NULL,
                'satker_id' => NULL,
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Sekretaris Kementerian Pemuda dan Olahraga',
            ),
            15 => 
            array (
                'id' => 36,
                'nama' => 'Syaifuddin, SE, MM',
                'nip' => '196412312017051001',
                'golongan' => 'II/b',
                'pangkat' => 'Pengatur Muda Tk. I',
                'tahun_awal' => 2018,
                'tahun_akhir' => 2021,
                'satker_id' => '010101',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Kepala Biro Perencanaan dan Hubungan Masyarakat',
            ),
            16 => 
            array (
                'id' => 37,
                'nama' => 'Syaifuddin, SE, MM',
                'nip' => '196412312017051001',
                'golongan' => 'II/b',
                'pangkat' => 'Pengatur Muda Tk. I',
                'tahun_awal' => 2023,
                'tahun_akhir' => 2024,
                'satker_id' => '010101',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Kepala Biro Perencanaan dan Hubungan Masyarakat',
            ),
            17 => 
            array (
                'id' => 39,
                'nama' => 'M. Asichin',
                'nip' => '195303231979031001',
                'golongan' => 'IV/e',
                'pangkat' => 'Pembina Utama ',
                'tahun_awal' => 2010,
                'tahun_akhir' => 2013,
                'satker_id' => '',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Kepala Arsip Nasional RI',
            ),
            18 => 
            array (
                'id' => 40,
                'nama' => 'Drs. Asep Mukhtar Mawardi',
                'nip' => '19580809 198603 1 001',
                'golongan' => 'IV/c',
                'pangkat' => 'Pembina Utama Muda',
                'tahun_awal' => 2011,
                'tahun_akhir' => 2014,
                'satker_id' => '',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Direktur Pemanfaatan',
            ),
            19 => 
            array (
                'id' => 41,
                'nama' => 'DR.H. Susilo Bambang Yudhoyono',
                'nip' => '',
                'golongan' => '',
                'pangkat' => '',
                'tahun_awal' => 2004,
                'tahun_akhir' => 2014,
                'satker_id' => '',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Presiden Republik Indonesia',
            ),
            20 => 
            array (
                'id' => 42,
                'nama' => 'Dr. Mukhlis Paeni',
                'nip' => '',
                'golongan' => '',
                'pangkat' => '',
                'tahun_awal' => 1998,
                'tahun_akhir' => 2003,
                'satker_id' => '01',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Kepala ANRI',
            ),
            21 => 
            array (
                'id' => 43,
                'nama' => 'Dra. Soemartini',
                'nip' => '',
                'golongan' => '',
                'pangkat' => '',
                'tahun_awal' => 1982,
                'tahun_akhir' => 1991,
                'satker_id' => '01',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Kepala ANRI',
            ),
            22 => 
            array (
                'id' => 44,
                'nama' => 'Drs. Djoko Utomo, MA',
                'nip' => '',
                'golongan' => '',
                'pangkat' => '',
                'tahun_awal' => 2003,
                'tahun_akhir' => 2010,
                'satker_id' => '01',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Kepala ANRI',
            ),
            23 => 
            array (
                'id' => 45,
                'nama' => 'Rini Agustisni, SH',
                'nip' => '360 000 460',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk. I ',
                'tahun_awal' => 2008,
                'tahun_akhir' => 2014,
                'satker_id' => '',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Kepala Sub Direktorat Bina Arsiparis',
            ),
            24 => 
            array (
                'id' => 46,
                'nama' => 'Dr. Noerhadi Magetsasri',
                'nip' => '130 197 928',
                'golongan' => 'IV/e ',
                'pangkat' => 'Pembina Utama ',
                'tahun_awal' => 1991,
                'tahun_akhir' => 1995,
                'satker_id' => '01',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Kepala ANRI',
            ),
            25 => 
            array (
                'id' => 47,
                'nama' => 'Oman Sachroni',
                'nip' => '195906211987031001',
                'golongan' => 'IV/e ',
                'pangkat' => 'Pembina Utama ',
                'tahun_awal' => 2003,
                'tahun_akhir' => 2008,
                'satker_id' => '01',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Kepala ANRI',
            ),
            26 => 
            array (
                'id' => 1047,
                'nama' => 'Dr.Mustari Irawan, M.P.A',
                'nip' => '195906211987031001',
                'golongan' => 'IV/e ',
                'pangkat' => 'Pembina Utama ',
                'tahun_awal' => 2013,
                'tahun_akhir' => 2018,
                'satker_id' => '01',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Kepala ANRI',
            ),
            27 => 
            array (
                'id' => 1048,
                'nama' => 'Drs. Sumrahyadi, MIMS',
                'nip' => '19611009 198703 1 001',
                'golongan' => '',
                'pangkat' => '',
                'tahun_awal' => 2015,
                'tahun_akhir' => 2017,
                'satker_id' => '',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Sekretaris Utama',
            ),
            28 => 
            array (
                'id' => 2057,
                'nama' => 'Drs. A. Radjak Fadli',
                'nip' => '',
                'golongan' => '',
                'pangkat' => '',
                'tahun_awal' => 2001,
                'tahun_akhir' => 2005,
                'satker_id' => '',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Kepala Biro Perencanaan , Kepegawaiaan dan Hukum',
            ),
            29 => 
            array (
                'id' => 3057,
                'nama' => 'Desti Trisfati Dwi Putri, SAP, M.AP ',
                'nip' => '197812262000032001',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk. I',
                'tahun_awal' => 2019,
                'tahun_akhir' => 2019,
                'satker_id' => '01010202',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Kepala Bagian Kepegawaian',
            ),
            30 => 
            array (
                'id' => 3058,
                'nama' => 'DR. M. TAUFIK,MSI',
                'nip' => '196004271981031001',
                'golongan' => 'IV/e ',
                'pangkat' => 'Pembina Utama ',
                'tahun_awal' => 2019,
                'tahun_akhir' => 2020,
                'satker_id' => '01',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Kepala ANRI',
            ),
            31 => 
            array (
                'id' => 4058,
                'nama' => 'Dr. M. TAUFIK,M.Si',
                'nip' => '19600427 19981031001',
                'golongan' => '',
                'pangkat' => '',
                'tahun_awal' => 2019,
                'tahun_akhir' => 2020,
                'satker_id' => '',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Plt. KEPALA ARSIP NASIONAL REPUBLIK INDONESIA',
            ),
            32 => 
            array (
                'id' => 4059,
                'nama' => 'DRS. IMAM GUNARTO,M.Hum',
                'nip' => '19630728 199203 1 001',
                'golongan' => 'IV/e ',
                'pangkat' => 'Pembina Utama ',
                'tahun_awal' => 2020,
                'tahun_akhir' => 2025,
                'satker_id' => '0101',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'SEKRETARIS UTAMA',
            ),
            33 => 
            array (
                'id' => 4060,
                'nama' => 'GINA MASUDAH HUSNI',
                'nip' => '',
                'golongan' => '',
                'pangkat' => '',
                'tahun_awal' => 2010,
                'tahun_akhir' => 2015,
                'satker_id' => '',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'SEKRETARIS UTAMA ',
            ),
            34 => 
            array (
                'id' => 4061,
                'nama' => 'GINA MASUDAH HUSNI',
                'nip' => '196110091987031001',
                'golongan' => 'IV/e ',
                'pangkat' => 'Pembina Utama ',
                'tahun_awal' => 2010,
                'tahun_akhir' => 2015,
                'satker_id' => '0101',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Sekretaris Utama',
            ),
            35 => 
            array (
                'id' => 4062,
                'nama' => 'MEGAWATI SOEKARNOPUTRI',
                'nip' => '',
                'golongan' => '',
                'pangkat' => '',
                'tahun_awal' => 2003,
                'tahun_akhir' => 2009,
                'satker_id' => '',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'PRESIDEN REPUBLIK INDONESIA',
            ),
            36 => 
            array (
                'id' => 4063,
                'nama' => 'Dr.H.SUSILO BAMBANG YUDHOYONO',
                'nip' => '',
                'golongan' => '',
                'pangkat' => '',
                'tahun_awal' => 2009,
                'tahun_akhir' => 2014,
                'satker_id' => '',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'PRESIDEN REPUBLIK INDONESIA',
            ),
            37 => 
            array (
                'id' => 4064,
                'nama' => 'D.SUDARHO,SH',
                'nip' => '',
                'golongan' => '',
                'pangkat' => '',
                'tahun_awal' => 1990,
                'tahun_akhir' => 1995,
                'satker_id' => '',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'SEKRETARIS',
            ),
            38 => 
            array (
                'id' => 4065,
                'nama' => 'D. SUDARNO, SH',
                'nip' => '',
                'golongan' => '',
                'pangkat' => '',
                'tahun_awal' => 1990,
                'tahun_akhir' => 1995,
                'satker_id' => '',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'SEKRETARIS',
            ),
            39 => 
            array (
                'id' => 4066,
                'nama' => 'MUKHLIS PAENI',
                'nip' => '',
                'golongan' => '',
                'pangkat' => '',
                'tahun_awal' => 1999,
                'tahun_akhir' => 2005,
                'satker_id' => '',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'KEPALA ARSIP NASIONAL REPUBLIK INDONESIA',
            ),
            40 => 
            array (
                'id' => 4067,
                'nama' => 'DESTI TRISFATI DWI PUTRI, SAP,MAP',
                'nip' => '197812262000032001',
                'golongan' => 'IV/A',
                'pangkat' => 'PEMBINA ',
                'tahun_awal' => 2020,
                'tahun_akhir' => 2023,
                'satker_id' => ' ',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'ANALIS KEPEGAWAIAN MADYA Selaku Koordinator Kelompok Substansi Kepegawaian',
            ),
            41 => 
            array (
                'id' => 4068,
                'nama' => 'SUMEH ABDUL HAMID',
                'nip' => '',
                'golongan' => '',
                'pangkat' => '',
                'tahun_awal' => 1998,
                'tahun_akhir' => 2003,
                'satker_id' => '',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'SEKRETARIS',
            ),
            42 => 
            array (
                'id' => 4069,
                'nama' => 'M. ASICHIN',
                'nip' => '',
                'golongan' => '',
                'pangkat' => '',
                'tahun_awal' => 2008,
                'tahun_akhir' => 2011,
                'satker_id' => '',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'SEKRETARIS UTAMA',
            ),
            43 => 
            array (
                'id' => 4070,
                'nama' => 'L. SOEPARNO',
                'nip' => '',
                'golongan' => '',
                'pangkat' => '',
                'tahun_awal' => 1993,
                'tahun_akhir' => 1998,
                'satker_id' => '',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'SEKRETARIS',
            ),
            44 => 
            array (
                'id' => 4071,
                'nama' => 'DRS. IMAM GUNARTO, M.Hum',
                'nip' => '19630728 199203 1 001',
                'golongan' => 'IV/e',
                'pangkat' => 'PEMBINA UTAMA',
                'tahun_awal' => 2021,
                'tahun_akhir' => 2023,
                'satker_id' => '01',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'KEPALA ARSIP NASIONAL REPUBLK INDONESIA',
            ),
            45 => 
            array (
                'id' => 4072,
                'nama' => 'Desti Trisfati Dwi Putri, SAP, M.A.P',
                'nip' => '197812262000032001',
                'golongan' => 'IV/a',
                'pangkat' => 'Pembina',
                'tahun_awal' => 2020,
                'tahun_akhir' => 2023,
                'satker_id' => '',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Koordinator Kelompok  Substansi Kepegawaian',
            ),
            46 => 
            array (
                'id' => 4073,
                'nama' => 'RINI AGUSTIANI, SH,MAP',
                'nip' => '19660818 199203 2 001',
                'golongan' => 'IV/d',
                'pangkat' => 'PEMBINA UTAMA MADYA',
                'tahun_awal' => 2021,
                'tahun_akhir' => 2025,
                'satker_id' => ' ',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'SEKRETARIS UTAMA',
            ),
            47 => 
            array (
                'id' => 4074,
                'nama' => 'Drs. A. Hadi Abubakar',
                'nip' => '180 000 236',
                'golongan' => '',
                'pangkat' => '',
                'tahun_awal' => 1985,
                'tahun_akhir' => 1990,
                'satker_id' => '',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Sekretaris Arsip Nasional RI',
            ),
            48 => 
            array (
                'id' => 5074,
                'nama' => 'DRS. AMIEKA HASRAF,MM',
                'nip' => '196607291994031001',
                'golongan' => 'IV/d',
                'pangkat' => 'Pembina Utama Madya',
                'tahun_awal' => 2022,
                'tahun_akhir' => 2025,
                'satker_id' => '',
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'KEPALA BIRO ORGANISASI KEPEGAWAIAN DAN HUKUM',
            ),
            49 => 
            array (
                'id' => 1,
                'nama' => 'Imam Nahrawi',
                'nip' => ' ',
                'golongan' => NULL,
                'pangkat' => NULL,
                'tahun_awal' => NULL,
                'tahun_akhir' => NULL,
                'satker_id' => NULL,
                'created_at' => '2023-07-01 07:47:46',
                'updated_at' => '2023-07-01 07:49:41',
                'jabatan' => 'Menteri Pemuda Dan Olahraga',
            ),
        ));
        
        
    }
}