<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CustomizedPenempatanPegawaiTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('penempatan_pegawai')->delete();
        
        \DB::table('penempatan_pegawai')->insert(array (
            0 => 
            array (
                'id' => 4,
                'unit_id' => 1,
                'nama_unitkerja' => 'Biro Perencanaan dan Hubungan Masyarakat',
                'jabatan_id' => 190,
                'nama_jabatan' => 'Arsiparis Ahli Madya',
                'kebutuhan' => 0,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 0,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 23,
                'unit_id' => 40,
                'nama_unitkerja' => 'Biro Umum',
                'jabatan_id' => 239,
                'nama_jabatan' => 'Analis Pengelolaan Keuangan APBN Ahli Pertama',
                'kebutuhan' => 0,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 0,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 37,
                'unit_id' => 40,
                'nama_unitkerja' => 'Biro Umum',
                'jabatan_id' => 225,
                'nama_jabatan' => 'Pranata Komputer Penyelia',
                'kebutuhan' => 0,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 0,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 7,
                'unit_id' => 1,
                'nama_unitkerja' => 'Biro Perencanaan dan Hubungan Masyarakat',
                'jabatan_id' => 170,
                'nama_jabatan' => 'Perencana Ahli Madya',
                'kebutuhan' => 7,
                'existing_pegawai' => 1,
                'kelebihan_kekurangan' => 6,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            4 => 
            array (
                'id' => 8,
                'unit_id' => 1,
                'nama_unitkerja' => 'Biro Perencanaan dan Hubungan Masyarakat',
                'jabatan_id' => 169,
                'nama_jabatan' => 'Perencana Ahli Muda',
                'kebutuhan' => 11,
                'existing_pegawai' => 1,
                'kelebihan_kekurangan' => 10,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            5 => 
            array (
                'id' => 9,
                'unit_id' => 1,
                'nama_unitkerja' => 'Biro Perencanaan dan Hubungan Masyarakat',
                'jabatan_id' => 188,
                'nama_jabatan' => 'Perencana Ahli Pertama',
                'kebutuhan' => 18,
                'existing_pegawai' => 4,
                'kelebihan_kekurangan' => 14,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            6 => 
            array (
                'id' => 1,
                'unit_id' => 1,
                'nama_unitkerja' => 'Biro Perencanaan dan Hubungan Masyarakat',
                'jabatan_id' => 231,
                'nama_jabatan' => 'Analis Anggaran Ahli Madya',
                'kebutuhan' => 1,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            7 => 
            array (
                'id' => 3,
                'unit_id' => 1,
                'nama_unitkerja' => 'Biro Perencanaan dan Hubungan Masyarakat',
                'jabatan_id' => 233,
                'nama_jabatan' => 'Analis Anggaran Ahli Pertama',
                'kebutuhan' => 1,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            8 => 
            array (
                'id' => 6,
                'unit_id' => 1,
                'nama_unitkerja' => 'Biro Perencanaan dan Hubungan Masyarakat',
                'jabatan_id' => 195,
                'nama_jabatan' => 'Arsiparis Ahli Pertama',
                'kebutuhan' => 1,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            9 => 
            array (
                'id' => 5,
                'unit_id' => 1,
                'nama_unitkerja' => 'Biro Perencanaan dan Hubungan Masyarakat',
                'jabatan_id' => 191,
                'nama_jabatan' => 'Arsiparis Ahli Muda',
                'kebutuhan' => 3,
                'existing_pegawai' => 2,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            10 => 
            array (
                'id' => 10,
                'unit_id' => 1,
                'nama_unitkerja' => 'Biro Perencanaan dan Hubungan Masyarakat',
                'jabatan_id' => 207,
                'nama_jabatan' => 'Pranata Hubungan Masyarakat Madya',
                'kebutuhan' => 3,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 3,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            11 => 
            array (
                'id' => 13,
                'unit_id' => 1,
                'nama_unitkerja' => 'Biro Perencanaan dan Hubungan Masyarakat',
                'jabatan_id' => 234,
                'nama_jabatan' => 'Pranata Hubungan Masyarakat Penyelia',
                'kebutuhan' => 3,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 3,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            12 => 
            array (
                'id' => 11,
                'unit_id' => 1,
                'nama_unitkerja' => 'Biro Perencanaan dan Hubungan Masyarakat',
                'jabatan_id' => 222,
                'nama_jabatan' => 'Pranata Hubungan Masyarakat Muda',
                'kebutuhan' => 5,
                'existing_pegawai' => 1,
                'kelebihan_kekurangan' => 4,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            13 => 
            array (
                'id' => 12,
                'unit_id' => 1,
                'nama_unitkerja' => 'Biro Perencanaan dan Hubungan Masyarakat',
                'jabatan_id' => 223,
                'nama_jabatan' => 'Pranata Hubungan Masyarakat Pertama',
                'kebutuhan' => 6,
                'existing_pegawai' => 3,
                'kelebihan_kekurangan' => 3,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            14 => 
            array (
                'id' => 14,
                'unit_id' => 1,
                'nama_unitkerja' => 'Biro Perencanaan dan Hubungan Masyarakat',
                'jabatan_id' => 235,
                'nama_jabatan' => 'Pranata Hubungan Masyarakat Mahir',
                'kebutuhan' => 2,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 2,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            15 => 
            array (
                'id' => 16,
                'unit_id' => 1,
                'nama_unitkerja' => 'Biro Perencanaan dan Hubungan Masyarakat',
                'jabatan_id' => 173,
                'nama_jabatan' => 'Pranata Komputer Ahli Muda',
                'kebutuhan' => 1,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            16 => 
            array (
                'id' => 15,
                'unit_id' => 1,
                'nama_unitkerja' => 'Biro Perencanaan dan Hubungan Masyarakat',
                'jabatan_id' => 236,
                'nama_jabatan' => 'Pranata Hubungan Masyarakat Terampil',
                'kebutuhan' => 2,
                'existing_pegawai' => 1,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            17 => 
            array (
                'id' => 17,
                'unit_id' => 1,
                'nama_unitkerja' => 'Biro Perencanaan dan Hubungan Masyarakat',
                'jabatan_id' => 176,
                'nama_jabatan' => 'Pranata Komputer Ahli Pertama',
                'kebutuhan' => 1,
                'existing_pegawai' => 1,
                'kelebihan_kekurangan' => 0,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            18 => 
            array (
                'id' => 18,
                'unit_id' => 1,
                'nama_unitkerja' => 'Biro Perencanaan dan Hubungan Masyarakat',
                'jabatan_id' => 175,
                'nama_jabatan' => 'Pranata Komputer Mahir',
                'kebutuhan' => 2,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 2,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            19 => 
            array (
                'id' => 19,
                'unit_id' => 1,
                'nama_unitkerja' => 'Biro Perencanaan dan Hubungan Masyarakat',
                'jabatan_id' => 174,
                'nama_jabatan' => 'Pranata Komputer Terampil',
                'kebutuhan' => 1,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            20 => 
            array (
                'id' => 20,
                'unit_id' => 1,
                'nama_unitkerja' => 'Biro Perencanaan dan Hubungan Masyarakat',
                'jabatan_id' => 26,
                'nama_jabatan' => 'Penelaah Teknis Kebijakan',
                'kebutuhan' => 7,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 7,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            21 => 
            array (
                'id' => 21,
                'unit_id' => 40,
                'nama_unitkerja' => 'Biro Umum',
                'jabatan_id' => 237,
                'nama_jabatan' => 'Analis Pengelolaan Keuangan APBN Ahli Madya',
                'kebutuhan' => 2,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 2,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            22 => 
            array (
                'id' => 24,
                'unit_id' => 40,
                'nama_unitkerja' => 'Biro Umum',
                'jabatan_id' => 190,
                'nama_jabatan' => 'Arsiparis Ahli Madya',
                'kebutuhan' => 2,
                'existing_pegawai' => 2,
                'kelebihan_kekurangan' => 0,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            23 => 
            array (
                'id' => 26,
                'unit_id' => 40,
                'nama_unitkerja' => 'Biro Umum',
                'jabatan_id' => 195,
                'nama_jabatan' => 'Arsiparis Ahli Pertama',
                'kebutuhan' => 10,
                'existing_pegawai' => 10,
                'kelebihan_kekurangan' => 0,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            24 => 
            array (
                'id' => 29,
                'unit_id' => 40,
                'nama_unitkerja' => 'Biro Umum',
                'jabatan_id' => 243,
                'nama_jabatan' => 'Arsiparis Terampil',
                'kebutuhan' => 5,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 5,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            25 => 
            array (
                'id' => 27,
                'unit_id' => 40,
                'nama_unitkerja' => 'Biro Umum',
                'jabatan_id' => 194,
                'nama_jabatan' => 'Arsiparis Penyelia',
                'kebutuhan' => 3,
                'existing_pegawai' => 2,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            26 => 
            array (
                'id' => 28,
                'unit_id' => 40,
                'nama_unitkerja' => 'Biro Umum',
                'jabatan_id' => 192,
                'nama_jabatan' => 'Arsiparis Pelaksana',
                'kebutuhan' => 4,
                'existing_pegawai' => 3,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            27 => 
            array (
                'id' => 30,
                'unit_id' => 40,
                'nama_unitkerja' => 'Biro Umum',
                'jabatan_id' => 240,
                'nama_jabatan' => 'Pranata Keuangan APBN Penyelia',
                'kebutuhan' => 7,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 7,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            28 => 
            array (
                'id' => 31,
                'unit_id' => 40,
                'nama_unitkerja' => 'Biro Umum',
                'jabatan_id' => 241,
                'nama_jabatan' => 'Pranata Keuangan APBN Mahir',
                'kebutuhan' => 8,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 8,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            29 => 
            array (
                'id' => 32,
                'unit_id' => 40,
                'nama_unitkerja' => 'Biro Umum',
                'jabatan_id' => 242,
                'nama_jabatan' => 'Pranata Keuangan APBN Terampil',
                'kebutuhan' => 9,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 9,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            30 => 
            array (
                'id' => 33,
                'unit_id' => 40,
                'nama_unitkerja' => 'Biro Umum',
                'jabatan_id' => 172,
                'nama_jabatan' => 'Pranata Komputer Ahli Madya',
                'kebutuhan' => 1,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            31 => 
            array (
                'id' => 34,
                'unit_id' => 40,
                'nama_unitkerja' => 'Biro Umum',
                'jabatan_id' => 173,
                'nama_jabatan' => 'Pranata Komputer Ahli Muda',
                'kebutuhan' => 2,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 2,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            32 => 
            array (
                'id' => 35,
                'unit_id' => 40,
                'nama_unitkerja' => 'Biro Umum',
                'jabatan_id' => 176,
                'nama_jabatan' => 'Pranata Komputer Ahli Pertama',
                'kebutuhan' => 3,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 3,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            33 => 
            array (
                'id' => 36,
                'unit_id' => 40,
                'nama_unitkerja' => 'Biro Umum',
                'jabatan_id' => 244,
                'nama_jabatan' => 'Pengelola PBJ Ahli Madya',
                'kebutuhan' => 1,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            34 => 
            array (
                'id' => 38,
                'unit_id' => 40,
                'nama_unitkerja' => 'Biro Umum',
                'jabatan_id' => 175,
                'nama_jabatan' => 'Pranata Komputer Mahir',
                'kebutuhan' => 1,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            35 => 
            array (
                'id' => 43,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 248,
                'nama_jabatan' => 'Apoteker Ahli Muda',
                'kebutuhan' => 1,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            36 => 
            array (
                'id' => 40,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 156,
                'nama_jabatan' => 'Analis Sumber Daya Manusia Aparatur Ahli Madya',
                'kebutuhan' => 9,
                'existing_pegawai' => 4,
                'kelebihan_kekurangan' => 5,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            37 => 
            array (
                'id' => 41,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 157,
                'nama_jabatan' => 'Analis Sumber Daya Manusia Aparatur Ahli Muda',
                'kebutuhan' => 12,
                'existing_pegawai' => 1,
                'kelebihan_kekurangan' => 11,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            38 => 
            array (
                'id' => 42,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 167,
                'nama_jabatan' => 'Analis Sumber Daya Manusia Aparatur Ahli Pertama',
                'kebutuhan' => 13,
                'existing_pegawai' => 7,
                'kelebihan_kekurangan' => 6,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            39 => 
            array (
                'id' => 44,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 247,
                'nama_jabatan' => 'Apoteker Ahli Pertama',
                'kebutuhan' => 1,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            40 => 
            array (
                'id' => 45,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 230,
                'nama_jabatan' => 'Asisten Apoteker Terampil',
                'kebutuhan' => 1,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            41 => 
            array (
                'id' => 46,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 226,
                'nama_jabatan' => 'Asesor Sumber Daya Manusia Aparatur Ahli Madya',
                'kebutuhan' => 3,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 3,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            42 => 
            array (
                'id' => 48,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 228,
                'nama_jabatan' => 'Asesor Sumber Daya Manusia Aparatur Ahli Pertama',
                'kebutuhan' => 7,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 7,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            43 => 
            array (
                'id' => 49,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 249,
                'nama_jabatan' => 'Dokter Ahli Madya',
                'kebutuhan' => 1,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            44 => 
            array (
                'id' => 50,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 250,
                'nama_jabatan' => 'Dokter Ahli Muda',
                'kebutuhan' => 1,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            45 => 
            array (
                'id' => 51,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 229,
                'nama_jabatan' => 'Dokter Ahli Pertama',
                'kebutuhan' => 3,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 3,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            46 => 
            array (
                'id' => 2,
                'unit_id' => 1,
                'nama_unitkerja' => 'Biro Perencanaan dan Hubungan Masyarakat',
                'jabatan_id' => 232,
                'nama_jabatan' => 'Analis Anggaran Ahli Muda',
                'kebutuhan' => 2,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 2,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            47 => 
            array (
                'id' => 25,
                'unit_id' => 40,
                'nama_unitkerja' => 'Biro Umum',
                'jabatan_id' => 191,
                'nama_jabatan' => 'Arsiparis Ahli Muda',
                'kebutuhan' => 7,
                'existing_pegawai' => 6,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            48 => 
            array (
                'id' => 39,
                'unit_id' => 40,
                'nama_unitkerja' => 'Biro Umum',
                'jabatan_id' => 174,
                'nama_jabatan' => 'Pranata Komputer Terampil',
                'kebutuhan' => 3,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 3,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            49 => 
            array (
                'id' => 47,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 227,
                'nama_jabatan' => 'Asesor Sumber Daya Manusia Aparatur Ahli Muda',
                'kebutuhan' => 5,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 5,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            50 => 
            array (
                'id' => 52,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 224,
                'nama_jabatan' => 'Perancang Peraturan Perundang-undangan Madya',
                'kebutuhan' => 4,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 4,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            51 => 
            array (
                'id' => 61,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 173,
                'nama_jabatan' => 'Pranata Komputer Ahli Muda',
                'kebutuhan' => 5,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 5,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            52 => 
            array (
                'id' => 53,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 217,
                'nama_jabatan' => 'Perancang Peraturan Perundang-undangan Muda',
                'kebutuhan' => 4,
                'existing_pegawai' => 3,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            53 => 
            array (
                'id' => 54,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 218,
                'nama_jabatan' => 'Perancang Peraturan Perundang-undangan Pertama',
                'kebutuhan' => 5,
                'existing_pegawai' => 2,
                'kelebihan_kekurangan' => 3,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            54 => 
            array (
                'id' => 55,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 251,
                'nama_jabatan' => 'Perawat Ahli Muda',
                'kebutuhan' => 1,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            55 => 
            array (
                'id' => 56,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 252,
                'nama_jabatan' => 'Perawat Ahli Pertama',
                'kebutuhan' => 2,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 2,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            56 => 
            array (
                'id' => 57,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 221,
                'nama_jabatan' => 'Perawat Penyelia',
                'kebutuhan' => 1,
                'existing_pegawai' => 1,
                'kelebihan_kekurangan' => 0,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            57 => 
            array (
                'id' => 58,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 219,
                'nama_jabatan' => 'Perawat Mahir',
                'kebutuhan' => 1,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            58 => 
            array (
                'id' => 59,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 220,
                'nama_jabatan' => 'Perawat Terampil',
                'kebutuhan' => 2,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 2,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            59 => 
            array (
                'id' => 60,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 172,
                'nama_jabatan' => 'Pranata Komputer Ahli Madya',
                'kebutuhan' => 1,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            60 => 
            array (
                'id' => 62,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 176,
                'nama_jabatan' => 'Pranata Komputer Ahli Pertama',
                'kebutuhan' => 2,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 2,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            61 => 
            array (
                'id' => 63,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 225,
                'nama_jabatan' => 'Pranata Komputer Penyelia',
                'kebutuhan' => 1,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            62 => 
            array (
                'id' => 64,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 175,
                'nama_jabatan' => 'Pranata Komputer Mahir',
                'kebutuhan' => 3,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 3,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:42',
            ),
            63 => 
            array (
                'id' => 65,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 174,
                'nama_jabatan' => 'Pranata Komputer Terampil',
                'kebutuhan' => 1,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:43',
            ),
            64 => 
            array (
                'id' => 66,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 158,
                'nama_jabatan' => 'Pranata Sumber Daya Manusia Aparatur Jenjang Penyelia',
                'kebutuhan' => 4,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 4,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:43',
            ),
            65 => 
            array (
                'id' => 67,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 159,
                'nama_jabatan' => 'Pranata Sumber Daya Manusia Aparatur Jenjang Mahir',
                'kebutuhan' => 4,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 4,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:43',
            ),
            66 => 
            array (
                'id' => 68,
                'unit_id' => 46,
                'nama_unitkerja' => 'Biro Organisansi, Kepegawaian dan Hukum',
                'jabatan_id' => 160,
                'nama_jabatan' => 'Pranata Sumber Daya Manusia Aparatur Jenjang Terampil',
                'kebutuhan' => 6,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 6,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:43',
            ),
            67 => 
            array (
                'id' => 22,
                'unit_id' => 40,
                'nama_unitkerja' => 'Biro Umum',
                'jabatan_id' => 238,
                'nama_jabatan' => 'Analis Pengelolaan Keuangan APBN Ahli Muda',
                'kebutuhan' => 5,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 5,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:43',
            ),
            68 => 
            array (
                'id' => 69,
                'unit_id' => 40,
                'nama_unitkerja' => 'Biro Umum',
                'jabatan_id' => 253,
                'nama_jabatan' => 'Pengadministrasi Perkantoran',
                'kebutuhan' => 2,
                'existing_pegawai' => 0,
                'kelebihan_kekurangan' => 2,
                'bulan' => 1,
                'tahun' => 2024,
                'created_at' => NULL,
                'updated_at' => '2024-01-23 03:46:43',
            ),
        ));
        
        
    }
}