<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CustomizedUnitKerjaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('unit_kerja')->delete();
        
        \DB::table('unit_kerja')->insert(array (
            0 => 
            array (
                'id' => 72,
                'parent_id' => 8,
                'name' => 'Subdirektorat SDM Kearsipan',
                'simpeg_id' => 72,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subdirektorat SDM Kearsipan',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 33,
                'old_id' => '01020401',
            ),
            1 => 
            array (
                'id' => 41,
                'parent_id' => 38,
                'name' => 'Sekretariat Utama',
                'simpeg_id' => 41,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Sekretaris Utama',
                'pejabat_nip' => '000000019',
                'pejabat_nama' => 'Rini Agustiani',
                'order' => 52,
                'old_id' => '0101',
            ),
            2 => 
            array (
                'id' => 1,
                'parent_id' => 41,
                'name' => 'Biro Perencanaan dan Hubungan Masyarakat',
                'simpeg_id' => 1,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Biro Perencanaan dan Hubungan Masyarakat',
                'pejabat_nip' => '000000000753',
                'pejabat_nama' => 'Drs. Florentinus Kristiartono, MM',
                'order' => 53,
                'old_id' => '010101',
            ),
            3 => 
            array (
                'id' => 2,
                'parent_id' => 103,
                'name' => 'Subbagian Perencanaan Program',
                'simpeg_id' => 2,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Perencanaan Program',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 61,
                'old_id' => '0101010101',
            ),
            4 => 
            array (
                'id' => 91,
                'parent_id' => 98,
                'name' => 'Subbagian Hubungan Antar Lembaga dan Protokol',
                'simpeg_id' => 91,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Hubungan Antar Lembaga dan Protokol',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 55,
                'old_id' => '0101010301',
            ),
            5 => 
            array (
                'id' => 112,
                'parent_id' => 98,
                'name' => 'Subbagian Tata Usaha Deputi Bidang Pembinaan Kearsipan',
                'simpeg_id' => 112,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Tata Usaha Deputi Bidang Pembinaan Kearsipan',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 56,
                'old_id' => '0101010303',
            ),
            6 => 
            array (
                'id' => 44,
                'parent_id' => 38,
                'name' => 'Deputi Bidang Pembinaan Kearsipan',
                'simpeg_id' => 44,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Deputi Bidang Pembinaan Kearsipan',
                'pejabat_nip' => '000000014',
                'pejabat_nama' => 'Desi Pratiwi',
                'order' => 2,
                'old_id' => '0102',
            ),
            7 => 
            array (
                'id' => 52,
                'parent_id' => 8,
                'name' => 'Subdirektorat Sertifikasi',
                'simpeg_id' => 52,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subdirektorat Sertifikasi',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 34,
                'old_id' => '01020402',
            ),
            8 => 
            array (
                'id' => 39,
                'parent_id' => 38,
                'name' => 'Deputi Bidang Konservasi Arsip',
                'simpeg_id' => 39,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Deputi Bidang Konservasi Arsip',
                'pejabat_nip' => '000000027',
                'pejabat_nama' => 'Kandar',
                'order' => 35,
                'old_id' => '0103',
            ),
            9 => 
            array (
                'id' => 9,
                'parent_id' => 39,
                'name' => 'Direktorat Akuisisi',
                'simpeg_id' => 9,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Direktur Akuisisi  ',
                'pejabat_nip' => '000000105',
                'pejabat_nama' => 'Wawan',
                'order' => 45,
                'old_id' => '010301',
            ),
            10 => 
            array (
                'id' => 55,
                'parent_id' => 9,
                'name' => 'Subdirektorat Akuisisi Arsip I',
                'simpeg_id' => 55,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subdirektorat Akuisisi Arsip I',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 46,
                'old_id' => '01030101',
            ),
            11 => 
            array (
                'id' => 77,
                'parent_id' => 9,
                'name' => 'Subdirektorat Akuisisi Arsip II',
                'simpeg_id' => 77,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subdirektorat Akuisisi Arsip II',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 48,
                'old_id' => '01030102',
            ),
            12 => 
            array (
                'id' => 62,
                'parent_id' => 9,
                'name' => 'Subdirektorat Akuisisi Arsip III',
                'simpeg_id' => 62,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subdirektorat Akuisisi Arsip III',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 47,
                'old_id' => '01030103',
            ),
            13 => 
            array (
                'id' => 10,
                'parent_id' => 39,
                'name' => 'Direktorat Pengolahan',
                'simpeg_id' => 10,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Direktur Pengolahan  ',
                'pejabat_nip' => '000000111',
                'pejabat_nama' => 'Wiwi Diana Sari',
                'order' => 36,
                'old_id' => '010302',
            ),
            14 => 
            array (
                'id' => 56,
                'parent_id' => 10,
                'name' => 'Subdirektorat Pengolahan Arsip I',
                'simpeg_id' => 56,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subdirektorat Pengolahan Arsip I',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 38,
                'old_id' => '01030201',
            ),
            15 => 
            array (
                'id' => 64,
                'parent_id' => 10,
                'name' => 'Subdirektorat Pengolahan Arsip II',
                'simpeg_id' => 64,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subdirektorat Pengolahan Arsip II',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 37,
                'old_id' => '01030202',
            ),
            16 => 
            array (
                'id' => 83,
                'parent_id' => 10,
                'name' => 'Subdirektorat Pengolahan Arsip III',
                'simpeg_id' => 83,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subdirektorat Pengolahan Arsip III',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 39,
                'old_id' => '01030203',
            ),
            17 => 
            array (
                'id' => 47,
                'parent_id' => 39,
                'name' => 'Direktorat Preservasi',
                'simpeg_id' => 47,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Direktur Preservasi',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 40,
                'old_id' => '010303',
            ),
            18 => 
            array (
                'id' => 94,
                'parent_id' => 47,
                'name' => 'Subdirektorat Penyimpanan Arsip',
                'simpeg_id' => 94,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subdirektorat Penyimpanan Arsip ',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 41,
                'old_id' => '01030301',
            ),
            19 => 
            array (
                'id' => 66,
                'parent_id' => 47,
                'name' => 'Subdirektorat Restorasi Arsip',
                'simpeg_id' => 66,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subdirektorat Restorasi Arsip',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 42,
                'old_id' => '01030302',
            ),
            20 => 
            array (
                'id' => 58,
                'parent_id' => 47,
                'name' => 'Subdirektorat Laboratorium dan Autentikasi Arsip',
                'simpeg_id' => 58,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subdirektorat Laboratorium dan Autentikasi Arsip',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 43,
                'old_id' => '01030304',
            ),
            21 => 
            array (
                'id' => 49,
                'parent_id' => 39,
                'name' => 'Direktorat Layanan dan Pemanfaatan',
                'simpeg_id' => 49,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Direktur Layanan dan Pemanfaatan',
                'pejabat_nip' => '000000112',
                'pejabat_nama' => 'Eli Ruliawati',
                'order' => 49,
                'old_id' => '010304',
            ),
            22 => 
            array (
                'id' => 68,
                'parent_id' => 49,
                'name' => 'Subdirektorat Layanan Arsip',
                'simpeg_id' => 68,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subdirektorat Layanan Arsip',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 50,
                'old_id' => '01030401',
            ),
            23 => 
            array (
                'id' => 84,
                'parent_id' => 49,
                'name' => 'Subdirektorat Pemanfaatan Arsip',
                'simpeg_id' => 84,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subdirektorat Pemanfaatan Arsip',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 51,
                'old_id' => '01030402',
            ),
            24 => 
            array (
                'id' => 18,
                'parent_id' => 22,
            'name' => 'PEGAWAI DIPEKERJAKAN DI LUAR ANRI (Badan Pengawas Keuangan Pembangunan)',
                'simpeg_id' => 18,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
            'pejabat_jabatan' => 'Kepala PEGAWAI DIPEKERJAKAN DI LUAR ANRI  (Badan Pengawas Keuangan Pembangunan)',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 25,
                'old_id' => '0201',
            ),
            25 => 
            array (
                'id' => 23,
                'parent_id' => 22,
            'name' => 'PEGAWAI DIPEKERJAKAN DI LUAR ANRI (Komisi Pemberantasan Korupsi)',
                'simpeg_id' => 23,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
            'pejabat_jabatan' => 'Kepala PEGAWAI DIPEKERJAKAN DI LUAR ANRI  (Komisi Pemberantasan Korupsi)',
                'pejabat_nip' => '',
                'pejabat_nama' => '',
                'order' => 16,
                'old_id' => '0202',
            ),
            26 => 
            array (
                'id' => 24,
                'parent_id' => 22,
            'name' => 'PEGAWAI DIPEKERJAKAN DI LUAR ANRI (Mahkamah Konstitusi)',
                'simpeg_id' => 24,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
            'pejabat_jabatan' => 'Kepala PEGAWAI DIPEKERJAKAN DI LUAR ANRI  (Mahkamah Konstitusi)',
                'pejabat_nip' => '',
                'pejabat_nama' => '',
                'order' => 17,
                'old_id' => '0203',
            ),
            27 => 
            array (
                'id' => 26,
                'parent_id' => 22,
            'name' => 'PEGAWAI DIPEKERJAKAN DI LUAR ANRI (Komisi Pemberantasan Korupsi)',
                'simpeg_id' => 26,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
            'pejabat_jabatan' => 'Kepala PEGAWAI DIPEKERJAKAN DI LUAR ANRI  (Komisi Pemberantasan Korupsi)',
                'pejabat_nip' => '',
                'pejabat_nama' => '',
                'order' => 18,
                'old_id' => '0205',
            ),
            28 => 
            array (
                'id' => 27,
                'parent_id' => 22,
            'name' => 'PEGAWAI DIPEKERJAKAN DI LUAR ANRI (Komisi Pemberantasan Korupsi)',
                'simpeg_id' => 27,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
            'pejabat_jabatan' => 'Kepala PEGAWAI DIPEKERJAKAN DI LUAR ANRI  (Komisi Pemberantasan Korupsi)',
                'pejabat_nip' => '',
                'pejabat_nama' => '',
                'order' => 28,
                'old_id' => '0206',
            ),
            29 => 
            array (
                'id' => 28,
                'parent_id' => 22,
            'name' => 'PEGAWAI DIPEKERJAKAN DI LUAR ANRI (Mahkamah Konstitusi)',
                'simpeg_id' => 28,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
            'pejabat_jabatan' => 'Kepala PEGAWAI DIPEKERJAKAN DI LUAR ANRI  (Mahkamah Konstitusi)',
                'pejabat_nip' => '',
                'pejabat_nama' => '',
                'order' => 19,
                'old_id' => '0207',
            ),
            30 => 
            array (
                'id' => 29,
                'parent_id' => 22,
            'name' => 'PEGAWAI DIPEKERJAKAN DI LUAR ANRI (Mahkamah Konstitusi)',
                'simpeg_id' => 29,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
            'pejabat_jabatan' => 'Kepala PEGAWAI DIPEKERJAKAN DI LUAR ANRI  (Mahkamah Konstitusi)',
                'pejabat_nip' => '',
                'pejabat_nama' => '',
                'order' => 20,
                'old_id' => '0208',
            ),
            31 => 
            array (
                'id' => 31,
                'parent_id' => 22,
            'name' => 'PEGAWAI DIPEKERJAKAN DI LUAR ANRI (Kementerian Koordiantor Kesejahteraan Rakyat)',
                'simpeg_id' => 31,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
            'pejabat_jabatan' => 'Kepala PEGAWAI DIPEKERJAKAN DI LUAR ANRI  (Kementerian Koordiantor Kesejahteraan Rakyat)',
                'pejabat_nip' => '',
                'pejabat_nama' => '',
                'order' => 21,
                'old_id' => '0210',
            ),
            32 => 
            array (
                'id' => 32,
                'parent_id' => 22,
            'name' => 'PEGAWAI DIPEKERJAKAN DI LUAR ANRI (Mahkamah Konstitusi)',
                'simpeg_id' => 32,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
            'pejabat_jabatan' => 'Kepala PEGAWAI DIPEKERJAKAN DI LUAR ANRI  (Mahkamah Konstitusi)',
                'pejabat_nip' => '',
                'pejabat_nama' => '',
                'order' => 22,
                'old_id' => '0211',
            ),
            33 => 
            array (
                'id' => 33,
                'parent_id' => 22,
            'name' => 'PEGAWAI DIPEKERJAKAN DI LUAR ANRI (Pusat Pelaporan dan Analisis Transaksi Keuangan)',
                'simpeg_id' => 33,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
            'pejabat_jabatan' => 'Kepala PEGAWAI DIPEKERJAKAN DI LUAR ANRI  (Pusat Pelaporan dan Analisis Transaksi Keuangan)',
                'pejabat_nip' => '',
                'pejabat_nama' => '',
                'order' => 30,
                'old_id' => '0212',
            ),
            34 => 
            array (
                'id' => 34,
                'parent_id' => 22,
            'name' => 'PEGAWAI DIPEKERJAKAN DI LUAR ANRI (Kementerian Koordiantor Kesejahteraan Rakyat)',
                'simpeg_id' => 34,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
            'pejabat_jabatan' => 'Kepala PEGAWAI DIPEKERJAKAN DI LUAR ANRI  (Kementerian Koordiantor Kesejahteraan Rakyat)',
                'pejabat_nip' => '',
                'pejabat_nama' => '',
                'order' => 23,
                'old_id' => '0213',
            ),
            35 => 
            array (
                'id' => 35,
                'parent_id' => 22,
            'name' => 'PEGAWAI DIPEKERJAKAN DI LUAR ANRI (Pusat Pelaporan dan Analisis Transaksi Keuangan)',
                'simpeg_id' => 35,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
            'pejabat_jabatan' => 'Kepala PEGAWAI DIPEKERJAKAN DI LUAR ANRI  (Pusat Pelaporan dan Analisis Transaksi Keuangan)',
                'pejabat_nip' => '',
                'pejabat_nama' => '',
                'order' => 31,
                'old_id' => '0214',
            ),
            36 => 
            array (
                'id' => 36,
                'parent_id' => 22,
            'name' => 'PEGAWAI DIPEKERJAKAN DI LUAR ANRI (Pusat Pelaporan dan Analisis Transaksi Keuangan)',
                'simpeg_id' => 36,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
            'pejabat_jabatan' => 'Kepala PEGAWAI DIPEKERJAKAN DI LUAR ANRI  (Pusat Pelaporan dan Analisis Transaksi Keuangan)',
                'pejabat_nip' => '',
                'pejabat_nama' => '',
                'order' => 24,
                'old_id' => '0215',
            ),
            37 => 
            array (
                'id' => 37,
                'parent_id' => 25,
                'name' => 'Unit Sementara',
                'simpeg_id' => 37,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Unit Sementara',
                'pejabat_nip' => '',
                'pejabat_nama' => '',
                'order' => 27,
                'old_id' => '03',
            ),
            38 => 
            array (
                'id' => 103,
                'parent_id' => 1,
                'name' => 'Bagian Perencanaan',
                'simpeg_id' => 103,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Bagian Perencanaan',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 60,
                'old_id' => '01010101',
            ),
            39 => 
            array (
                'id' => 105,
                'parent_id' => 103,
                'name' => 'Subbagian Perencanaan Anggaran',
                'simpeg_id' => 105,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Perencanaan Anggaran',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 62,
                'old_id' => '0101010102',
            ),
            40 => 
            array (
                'id' => 110,
                'parent_id' => 1,
                'name' => 'Bagian Kerjasama dan Evaluasi',
                'simpeg_id' => 110,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Bagian Kerjasama dan Evaluasi',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 63,
                'old_id' => '01010102',
            ),
            41 => 
            array (
                'id' => 108,
                'parent_id' => 110,
                'name' => 'Subbagian Kerjasama',
                'simpeg_id' => 108,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Kerjasama',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 64,
                'old_id' => '0101010201',
            ),
            42 => 
            array (
                'id' => 51,
                'parent_id' => 6,
                'name' => 'Subdirektorat Pusat I',
                'simpeg_id' => 51,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subdirektorat Pusat I',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 8,
                'old_id' => '01020101',
            ),
            43 => 
            array (
                'id' => 3,
                'parent_id' => 110,
                'name' => 'Subbagian Evaluasi dan Pelaporan',
                'simpeg_id' => 3,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Evaluasi dan Pelaporan',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 65,
                'old_id' => '0101010202',
            ),
            44 => 
            array (
                'id' => 107,
                'parent_id' => 98,
                'name' => 'Subbagian Publikasi dan Dokumentasi',
                'simpeg_id' => 107,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Publikasi dan Dokumentasi ',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 58,
                'old_id' => '0101010302',
            ),
            45 => 
            array (
                'id' => 134,
                'parent_id' => 98,
                'name' => 'Subbagian Tata Usaha Deputi Bidang Informasi dan Pengembangan Sistem Kearsipan',
                'simpeg_id' => 134,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Tata Usaha Deputi Bidang Konservasi Arsip',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 57,
                'old_id' => '0101010305',
            ),
            46 => 
            array (
                'id' => 46,
                'parent_id' => 41,
                'name' => 'Biro Organisasi, Kepegawaian dan Hukum',
                'simpeg_id' => 46,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Biro Organisasi, Kepegawaian dan Hukum',
                'pejabat_nip' => '000000031',
                'pejabat_nama' => 'Amieka Hasraf',
                'order' => 81,
                'old_id' => '010102',
            ),
            47 => 
            array (
                'id' => 74,
                'parent_id' => 46,
                'name' => 'Bagian Organisasi dan Tata Laksana',
                'simpeg_id' => 74,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Bagian Organisasi dan Tata Laksana',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 82,
                'old_id' => '01010201',
            ),
            48 => 
            array (
                'id' => 111,
                'parent_id' => 74,
                'name' => 'Subbagian Organisasi',
                'simpeg_id' => 111,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Organisasi',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 83,
                'old_id' => '0101020101',
            ),
            49 => 
            array (
                'id' => 95,
                'parent_id' => 74,
                'name' => 'Subbagian Tata Laksana',
                'simpeg_id' => 95,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Tata Laksana',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 84,
                'old_id' => '0101020102',
            ),
            50 => 
            array (
                'id' => 92,
                'parent_id' => 46,
                'name' => 'Bagian Kepegawaian',
                'simpeg_id' => 92,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Bagian Kepegawaian',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 85,
                'old_id' => '01010202',
            ),
            51 => 
            array (
                'id' => 104,
                'parent_id' => 92,
                'name' => 'Subbagian Perencanaan dan Mutasi Pegawai',
                'simpeg_id' => 104,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Perencanaan dan Mutasi Pegawai ',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 88,
                'old_id' => '0101020201',
            ),
            52 => 
            array (
                'id' => 117,
                'parent_id' => 92,
                'name' => 'Subbagian Pengelolaan Data dan Disiplin Pegawai',
                'simpeg_id' => 117,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Pengelolaan Data dan Disiplin Pegawai',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 86,
                'old_id' => '0101020202',
            ),
            53 => 
            array (
                'id' => 4,
                'parent_id' => 92,
                'name' => 'Subbagian Pengembangan dan Kesejahteraan Pegawai',
                'simpeg_id' => 4,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Pengembangan dan Kesejahteraan Pegawai',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 89,
                'old_id' => '0101020203',
            ),
            54 => 
            array (
                'id' => 113,
                'parent_id' => 92,
                'name' => 'Subbagian Jabatan Fungsional',
                'simpeg_id' => 113,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Jabatan Fungsional',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 87,
                'old_id' => '0101020204',
            ),
            55 => 
            array (
                'id' => 79,
                'parent_id' => 46,
                'name' => 'Bagian Hukum dan Perundang-undangan',
                'simpeg_id' => 79,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Bagian Hukum dan Perundang-undangan',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 90,
                'old_id' => '01010203',
            ),
            56 => 
            array (
                'id' => 76,
                'parent_id' => 79,
                'name' => 'Subbagian Hukum',
                'simpeg_id' => 76,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Hukum ',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 91,
                'old_id' => '0101020301',
            ),
            57 => 
            array (
                'id' => 109,
                'parent_id' => 79,
                'name' => 'Subbagian Perundang-undangan',
                'simpeg_id' => 109,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Perundang-undangan',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 92,
                'old_id' => '0101020302',
            ),
            58 => 
            array (
                'id' => 40,
                'parent_id' => 41,
                'name' => 'Biro Umum',
                'simpeg_id' => 40,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Biro Umum',
                'pejabat_nip' => '000000037',
                'pejabat_nama' => 'Sarip Hidayat',
                'order' => 66,
                'old_id' => '010103',
            ),
            59 => 
            array (
                'id' => 89,
                'parent_id' => 40,
                'name' => 'Bagian Keuangan',
                'simpeg_id' => 89,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Bagian Keuangan',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 67,
                'old_id' => '01010301',
            ),
            60 => 
            array (
                'id' => 99,
                'parent_id' => 89,
                'name' => 'Subbagian Pembukuan',
                'simpeg_id' => 99,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Pembukuan  ',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 68,
                'old_id' => '0101030102',
            ),
            61 => 
            array (
                'id' => 5,
                'parent_id' => 89,
                'name' => 'Subbagian Verifikasi',
                'simpeg_id' => 5,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Verifikasi  ',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 69,
                'old_id' => '0101030103',
            ),
            62 => 
            array (
                'id' => 90,
                'parent_id' => 81,
                'name' => 'Subbagian Pengadaan',
                'simpeg_id' => 90,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Pengadaan  ',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 76,
                'old_id' => '0101030201',
            ),
            63 => 
            array (
                'id' => 106,
                'parent_id' => 81,
                'name' => 'Subbagian Pengelolaan Barang',
                'simpeg_id' => 106,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Pengelolaan Barang',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 77,
                'old_id' => '0101030202',
            ),
            64 => 
            array (
                'id' => 93,
                'parent_id' => 81,
                'name' => 'Subbagian Pemeliharaan',
                'simpeg_id' => 93,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Pemeliharaan  ',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 78,
                'old_id' => '0101030203',
            ),
            65 => 
            array (
                'id' => 102,
                'parent_id' => 81,
                'name' => 'Subbagian Perlengkapan dan Rumah Tangga',
                'simpeg_id' => 102,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Perlengkapan dan Rumah Tangga',
                'pejabat_nip' => '000000285',
                'pejabat_nama' => 'Moch Maulana Akbar,S.E',
                'order' => 79,
                'old_id' => '0101030204',
            ),
            66 => 
            array (
                'id' => 88,
                'parent_id' => 81,
                'name' => 'Subbagian Protokol dan Pengamanan',
                'simpeg_id' => 88,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Protokol dan Pengamanan',
                'pejabat_nip' => '000000472',
                'pejabat_nama' => 'Andhika Budi Prasetyo, S.H.',
                'order' => 80,
                'old_id' => '0101030205',
            ),
            67 => 
            array (
                'id' => 53,
                'parent_id' => 40,
                'name' => 'Bagian Arsip',
                'simpeg_id' => 53,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Bagian Arsip',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 72,
                'old_id' => '01010303',
            ),
            68 => 
            array (
                'id' => 100,
                'parent_id' => 53,
                'name' => 'Subbagian Persuratan dan Arsip Aktif',
                'simpeg_id' => 100,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Persuratan dan Arsip Aktif',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 73,
                'old_id' => '0101030301',
            ),
            69 => 
            array (
                'id' => 11,
                'parent_id' => 38,
                'name' => 'Deputi Bidang Informasi dan Pengembangan Sistem Kearsipan',
                'simpeg_id' => 11,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Deputi Bidang Informasi dan Pengembangan Sistem Kearsipan  ',
                'pejabat_nip' => '000000011',
                'pejabat_nama' => 'Dr.Andi Kasman, SE, MM',
                'order' => 105,
                'old_id' => '0104',
            ),
            70 => 
            array (
                'id' => 14,
                'parent_id' => 38,
                'name' => 'Pusat Jasa Kearsipan',
                'simpeg_id' => 14,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Pusat Jasa Kearsipan',
                'pejabat_nip' => '000000106',
                'pejabat_nama' => 'Dipo Winarto',
                'order' => 93,
                'old_id' => '0105',
            ),
            71 => 
            array (
                'id' => 65,
                'parent_id' => 14,
                'name' => 'Bidang Jasa Penyimpanan dan Perawatan Arsip',
                'simpeg_id' => 65,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Bidang Jasa Penyimpanan dan Perawatan Arsip',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 94,
                'old_id' => '010502',
            ),
            72 => 
            array (
                'id' => 63,
                'parent_id' => 14,
                'name' => 'Bidang Jasa Sistem dan Penataan Arsip',
                'simpeg_id' => 63,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Bidang Jasa Sistem dan Penataan Arsip',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 95,
                'old_id' => '010503',
            ),
            73 => 
            array (
                'id' => 118,
                'parent_id' => 38,
                'name' => 'Balai Arsip Tsunami Aceh',
                'simpeg_id' => 118,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Balai Arsip Tsunami Aceh',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 97,
                'old_id' => '0107',
            ),
            74 => 
            array (
                'id' => 101,
                'parent_id' => 118,
                'name' => 'Subbagian Tata Usaha Balai Arsip Tsunami Aceh',
                'simpeg_id' => 101,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Tata Usaha Balai Arsip Tsunami Aceh',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 98,
                'old_id' => '010701',
            ),
            75 => 
            array (
                'id' => 19,
                'parent_id' => 118,
                'name' => 'Seksi Pengolahan dan Preservasi Balai Arsip Tsunami Aceh',
                'simpeg_id' => 19,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Seksi Pengolahan dan Preservasi Balai Arsip Tsunami Aceh',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 100,
                'old_id' => '010702',
            ),
            76 => 
            array (
                'id' => 20,
                'parent_id' => 118,
                'name' => 'Seksi Pelayanan Balai Arsip Tsunami Aceh',
                'simpeg_id' => 20,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Seksi Pelayanan Balai Arsip Tsunami Aceh',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 99,
                'old_id' => '010703',
            ),
            77 => 
            array (
                'id' => 42,
                'parent_id' => 38,
                'name' => 'Pusat Akreditasi Kearsipan',
                'simpeg_id' => 42,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Pusat Akreditasi Kearsipan',
                'pejabat_nip' => '000000029',
                'pejabat_nama' => 'Zita Asih Suprastiwi',
                'order' => 101,
                'old_id' => '0108',
            ),
            78 => 
            array (
                'id' => 87,
                'parent_id' => 42,
                'name' => 'Subbagian Tata Usaha Akreditasi Kearsipan',
                'simpeg_id' => 87,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Tata Usaha Akreditasi Kearsipan',
                'pejabat_nip' => '000000409',
                'pejabat_nama' => 'Lisa Nurlaila Ningsih, S.AP',
                'order' => 104,
                'old_id' => '010801',
            ),
            79 => 
            array (
                'id' => 75,
                'parent_id' => 42,
                'name' => 'Bidang Akreditasi Daerah',
                'simpeg_id' => 75,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Bidang Akreditasi Daerah',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 102,
                'old_id' => '010802',
            ),
            80 => 
            array (
                'id' => 21,
                'parent_id' => 42,
                'name' => 'Bidang Akreditasi Pusat',
                'simpeg_id' => 21,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Bidang Akreditasi Pusat',
                'pejabat_nip' => '',
                'pejabat_nama' => '',
                'order' => 103,
                'old_id' => '010803',
            ),
            81 => 
            array (
                'id' => 25,
                'parent_id' => 22,
            'name' => 'PEGAWAI DIPEKERJAKAN DI LUAR ANRI (Kementerian Koordiantor Kesejahteraan Rakyat)',
                'simpeg_id' => 25,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
            'pejabat_jabatan' => 'Kepala PEGAWAI DIPEKERJAKAN DI LUAR ANRI  (Kementerian Koordiantor Kesejahteraan Rakyat)',
                'pejabat_nip' => '',
                'pejabat_nama' => '',
                'order' => 26,
                'old_id' => '0204',
            ),
            82 => 
            array (
                'id' => 38,
                'parent_id' => 0,
                'name' => 'Arsip Nasional Republik Indonesia',
                'simpeg_id' => 38,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala ANRI',
                'pejabat_nip' => '000000009',
                'pejabat_nama' => 'Imam Gunarto',
                'order' => 1,
                'old_id' => '01',
            ),
            83 => 
            array (
                'id' => 98,
                'parent_id' => 1,
                'name' => 'Bagian Hubungan Masyarakat dan Tata Usaha Pimpinan',
                'simpeg_id' => 98,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Bagian Hubungan Masyarakat dan Tata Usaha Pimpinan',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 54,
                'old_id' => '01010103',
            ),
            84 => 
            array (
                'id' => 127,
                'parent_id' => 98,
                'name' => 'Subbagian Tata Usaha Deputi Bidang Konservasi Arsip',
                'simpeg_id' => 127,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Tata Usaha Deputi Bidang Konservasi Arsip',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 59,
                'old_id' => '0101010304',
            ),
            85 => 
            array (
                'id' => 96,
                'parent_id' => 89,
                'name' => 'Subbagian Perbendaharaan',
                'simpeg_id' => 96,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Perbendaharaan ',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 70,
                'old_id' => '0101030101',
            ),
            86 => 
            array (
                'id' => 81,
                'parent_id' => 40,
                'name' => 'Bagian Perlengkapan, Tata Usaha, Kearsipan, dan Protokol',
                'simpeg_id' => 81,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Bagian Perlengkapan, Tata Usaha, Kearsipan, dan Protokol',
                'pejabat_nip' => '000000158',
                'pejabat_nama' => 'Furqon Imamsyah Ahda',
                'order' => 75,
                'old_id' => '01010302',
            ),
            87 => 
            array (
                'id' => 6,
                'parent_id' => 44,
                'name' => 'Direktorat Kearsipan Pusat',
                'simpeg_id' => 6,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Direktur Kearsipan Pusat',
                'pejabat_nip' => '000000013',
                'pejabat_nama' => 'Muhammad Imam Mulyantono',
                'order' => 7,
                'old_id' => '010201',
            ),
            88 => 
            array (
                'id' => 70,
                'parent_id' => 6,
                'name' => 'Subdirektorat Pusat II',
                'simpeg_id' => 70,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subdirektorat Pusat II',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 9,
                'old_id' => '01020102',
            ),
            89 => 
            array (
                'id' => 61,
                'parent_id' => 6,
                'name' => 'Subdirektorat Pusat III',
                'simpeg_id' => 61,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subdirektorat Pusat III',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 10,
                'old_id' => '01020103',
            ),
            90 => 
            array (
                'id' => 69,
                'parent_id' => 44,
                'name' => 'Direktorat Kearsipan Daerah I',
                'simpeg_id' => 69,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Direktur Kearsipan Daerah I',
                'pejabat_nip' => '000000008',
                'pejabat_nama' => 'Rudi Anton',
                'order' => 11,
                'old_id' => '010202',
            ),
            91 => 
            array (
                'id' => 57,
                'parent_id' => 69,
                'name' => 'Subdirektorat Daerah I A',
                'simpeg_id' => 57,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subdirektorat Daerah I A',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 12,
                'old_id' => '01020201',
            ),
            92 => 
            array (
                'id' => 78,
                'parent_id' => 69,
                'name' => 'Subdirektorat Daerah I B',
                'simpeg_id' => 78,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subdirektorat Daerah I B',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 13,
                'old_id' => '01020202',
            ),
            93 => 
            array (
                'id' => 54,
                'parent_id' => 69,
                'name' => 'Subdirektorat Daerah I C',
                'simpeg_id' => 54,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subdirektorat Daerah I C',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 14,
                'old_id' => '01020203',
            ),
            94 => 
            array (
                'id' => 80,
                'parent_id' => 44,
                'name' => 'Direktorat Kearsipan Daerah II',
                'simpeg_id' => 80,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Direktur Kearsipan Daerah II',
                'pejabat_nip' => '000000108',
                'pejabat_nama' => 'Suminarsih',
                'order' => 3,
                'old_id' => '010203',
            ),
            95 => 
            array (
                'id' => 50,
                'parent_id' => 80,
                'name' => 'Subdirektorat Daerah II A',
                'simpeg_id' => 50,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subdirektorat Daerah II A',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 4,
                'old_id' => '01020301',
            ),
            96 => 
            array (
                'id' => 60,
                'parent_id' => 80,
                'name' => 'Subdirektorat Daerah II B',
                'simpeg_id' => 60,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subdirektorat Daerah II B',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 6,
                'old_id' => '01020302',
            ),
            97 => 
            array (
                'id' => 7,
                'parent_id' => 80,
                'name' => 'Subdirektorat Daerah II C',
                'simpeg_id' => 7,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subdirektorat Daerah II C',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 5,
                'old_id' => '01020303',
            ),
            98 => 
            array (
                'id' => 8,
                'parent_id' => 44,
                'name' => 'Direktorat SDM Kearsipan dan Sertifikasi',
                'simpeg_id' => 8,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Direktur SDM Kearsipan dan Sertifikasi',
                'pejabat_nip' => '000000000754',
                'pejabat_nama' => 'Dr. Andi Abubakar, S.IP., M.Si',
                'order' => 32,
                'old_id' => '010204',
            ),
            99 => 
            array (
                'id' => 73,
                'parent_id' => 47,
                'name' => 'Subdirektorat Reproduksi dan Digitalisasi Arsip',
                'simpeg_id' => 73,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subdirektorat Reproduksi dan Digitalisasi Arsip',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 44,
                'old_id' => '01030303',
            ),
            100 => 
            array (
                'id' => 12,
                'parent_id' => 11,
                'name' => 'Pusat Sistem dan Jaringan Informasi Kearsipan Nasional',
                'simpeg_id' => 12,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Pusat Sistem dan Jaringan Informasi Kearsipan Nasional',
                'pejabat_nip' => '000000050',
                'pejabat_nama' => 'Listianingtyas Murgiwati.',
                'order' => 106,
                'old_id' => '010401',
            ),
            101 => 
            array (
                'id' => 86,
                'parent_id' => 12,
                'name' => 'Bidang Pengembangan Sistem dan Jaringan Informasi Kearsipan Nasional',
                'simpeg_id' => 86,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Bidang Pengembangan Sistem dan Jaringan Informasi Kearsipan Nasional',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 107,
                'old_id' => '01040101',
            ),
            102 => 
            array (
                'id' => 59,
                'parent_id' => 12,
                'name' => 'Bidang Pengembangan Simpul Jaringan',
                'simpeg_id' => 59,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Bidang Pengembangan Simpul Jaringan ',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 108,
                'old_id' => '01040102',
            ),
            103 => 
            array (
                'id' => 135,
                'parent_id' => 0,
                'name' => 'Pusat Studi Arsip Statis Kepresidenan',
                'simpeg_id' => 135,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Pusat Studi Arsip Statis Kepresidenan',
                'pejabat_nip' => '000000097',
                'pejabat_nama' => 'Mira Puspita Rini',
                'order' => 121,
                'old_id' => '0110',
            ),
            104 => 
            array (
                'id' => 22,
                'parent_id' => 54,
                'name' => 'Dipekerjakan',
                'simpeg_id' => 22,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Dipekerjakan',
                'pejabat_nip' => '',
                'pejabat_nama' => '',
                'order' => 15,
                'old_id' => '02',
            ),
            105 => 
            array (
                'id' => 115,
                'parent_id' => 89,
                'name' => 'Subbagian Akuntansi dan Pelaporan',
                'simpeg_id' => 115,
                'created_at' => '2023-07-15 00:42:13',
                'updated_at' => '2023-07-15 00:42:13',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Akuntansi dan Pelaporan',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 1,
                'old_id' => NULL,
            ),
            106 => 
            array (
                'id' => 116,
                'parent_id' => 53,
                'name' => 'Subbagian Pengelolaan Arsip Inaktif',
                'simpeg_id' => 116,
                'created_at' => '2023-07-15 00:42:13',
                'updated_at' => '2023-07-15 00:42:13',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Pengelolaan Arsip In Aktif',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 1,
                'old_id' => NULL,
            ),
            107 => 
            array (
                'id' => 114,
                'parent_id' => 14,
                'name' => 'Subbagian Tata Usaha Pusat Jasa Kearsipan',
                'simpeg_id' => 114,
                'created_at' => '2023-07-15 00:42:13',
                'updated_at' => '2023-07-15 00:42:13',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Tata Usaha Pusat Jasa Kearsipan  ',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 1,
                'old_id' => NULL,
            ),
            108 => 
            array (
                'id' => 30,
                'parent_id' => 22,
            'name' => 'PEGAWAI DIPEKERJAKAN DI LUAR ANRI (Komisi Pemberantasan Korupsi)',
                'simpeg_id' => 30,
                'created_at' => '2023-07-15 00:42:13',
                'updated_at' => '2023-07-15 00:42:13',
                'path' => NULL,
            'pejabat_jabatan' => 'Kepala PEGAWAI DIPEKERJAKAN DI LUAR ANRI  (Komisi Pemberantasan Korupsi)',
                'pejabat_nip' => '',
                'pejabat_nama' => '',
                'order' => 1,
                'old_id' => NULL,
            ),
            109 => 
            array (
                'id' => 45,
                'parent_id' => 11,
                'name' => 'Pusat Data dan Informasi',
                'simpeg_id' => 45,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Pusat Data dan Informasi',
                'pejabat_nip' => '000000068',
                'pejabat_nama' => 'Hilman Rosmana',
                'order' => 109,
                'old_id' => '010402',
            ),
            110 => 
            array (
                'id' => 85,
                'parent_id' => 45,
                'name' => 'Bidang Pengelolaan Data dan Informasi',
                'simpeg_id' => 85,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Bidang Pengelolaan Data dan Informasi',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 110,
                'old_id' => '01040201',
            ),
            111 => 
            array (
                'id' => 13,
                'parent_id' => 45,
                'name' => 'Bidang Pengelolaan Perangkat TIK dan Sistem Informasi',
                'simpeg_id' => 13,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Bidang Pengelolaan Perangkat TIK dan Sistem Informasi',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 111,
                'old_id' => '01040202',
            ),
            112 => 
            array (
                'id' => 48,
                'parent_id' => 11,
                'name' => 'Pusat Pengkajian dan Pengembangan Sistem Kearsipan',
                'simpeg_id' => 48,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Pusat Pengkajian dan Pengembangan Sistem Kearsipan',
                'pejabat_nip' => '000000030',
                'pejabat_nama' => 'Muhammad Sumitro',
                'order' => 112,
                'old_id' => '010403',
            ),
            113 => 
            array (
                'id' => 82,
                'parent_id' => 48,
                'name' => 'Bidang Sistem Kearsipan Dinamis',
                'simpeg_id' => 82,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Bidang Sistem Kearsipan Dinamis',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 113,
                'old_id' => '01040301',
            ),
            114 => 
            array (
                'id' => 67,
                'parent_id' => 48,
                'name' => 'Bidang Sistem Kearsipan Statis',
                'simpeg_id' => 67,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Bidang Sistem Kearsipan Statis',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 114,
                'old_id' => '01040302',
            ),
            115 => 
            array (
                'id' => 43,
                'parent_id' => 38,
                'name' => 'Inspektorat',
                'simpeg_id' => 43,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Inspektur',
                'pejabat_nip' => '000000010',
                'pejabat_nama' => 'Syaifuddin',
                'order' => 115,
                'old_id' => '0106',
            ),
            116 => 
            array (
                'id' => 97,
                'parent_id' => 43,
                'name' => 'Subbagian Tata Usaha Inspektorat',
                'simpeg_id' => 97,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Tata Usaha Inspektorat ',
                'pejabat_nip' => '000000506',
                'pejabat_nama' => 'Radmoko Nugroho, S.AP',
                'order' => 116,
                'old_id' => '010601',
            ),
            117 => 
            array (
                'id' => 15,
                'parent_id' => 38,
                'name' => 'Pusat Pendidikan dan Pelatihan Kearsipan',
                'simpeg_id' => 15,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Pusat Pendidikan dan Pelatihan Kearsipan',
                'pejabat_nip' => '000000012',
                'pejabat_nama' => 'Widarno',
                'order' => 117,
                'old_id' => '0109',
            ),
            118 => 
            array (
                'id' => 16,
                'parent_id' => 15,
                'name' => 'Subbagian Tata Usaha Pusat Pendidikan dan Pelatihan Kearsipan',
                'simpeg_id' => 16,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Tata Usaha Pusat Pendidikan dan Pelatihan Kearsipan',
                'pejabat_nip' => '000000426',
                'pejabat_nama' => 'Achmad Sabiqun Nahar, S.AP',
                'order' => 118,
                'old_id' => '010901',
            ),
            119 => 
            array (
                'id' => 71,
                'parent_id' => 15,
                'name' => 'Bidang Pelaksanaan dan Kerja Sama Pendidikan dan Pelatihan Kearsipan',
                'simpeg_id' => 71,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Bidang Pelaksanaan dan Kerja Sama Pendidikan dan Pelatihan Kearsipan',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 120,
                'old_id' => '010902',
            ),
            120 => 
            array (
                'id' => 17,
                'parent_id' => 15,
                'name' => 'Bidang Perencanaan dan Evaluasi Pendidikan dan Pelatihan Kearsipan',
                'simpeg_id' => 17,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Bidang Perencanaan dan Evaluasi Pendidikan dan Pelatihan Kearsipan',
                'pejabat_nip' => NULL,
                'pejabat_nama' => NULL,
                'order' => 119,
                'old_id' => '010903',
            ),
            121 => 
            array (
                'id' => 136,
                'parent_id' => 0,
                'name' => 'Subbagian Umum Pusat Studi Arsip Statis Kepresidenan',
                'simpeg_id' => 136,
                'created_at' => '2023-06-27 00:43:01',
                'updated_at' => '2023-07-14 12:49:40',
                'path' => NULL,
                'pejabat_jabatan' => 'Kepala Subbagian Umum Pusat Studi Arsip Statis Kepresidenan',
                'pejabat_nip' => NULL,
                'pejabat_nama' => '',
                'order' => 122,
                'old_id' => '011001',
            ),
        ));
        
        
    }
}