<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CustomizedHukumanTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('hukuman')->delete();
        
        \DB::table('hukuman')->insert(array (
            0 => 
            array (
                'id' => 32,
                'parent_id' => NULL,
                'simpeg_id' => '9.',
                'hukuman' => 'Berdasarkan UUD 45',
                'jenis' => '0',
                'jumlah_min' => '0',
                'jumlah_max' => NULL,
                'jenis_efek' => '0',
                'durasi_efek' => '0',
                'proses' => '0',
                'rentang' => '0',
                'efek' => '0',
                'tingkat' => '0',
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:26:35',
                'order' => 1,
                'siasn_id' => NULL,
                'id_tingkat' => NULL,
            ),
            1 => 
            array (
                'id' => 16,
                'parent_id' => 15,
                'simpeg_id' => '10.2.',
                'hukuman' => 'Peraturan Gubernur',
                'jenis' => NULL,
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => NULL,
                'durasi_efek' => NULL,
                'proses' => NULL,
                'rentang' => NULL,
                'efek' => '0',
                'tingkat' => '0',
                'keterangan' => 'Peraturan Gubernur',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:25:45',
                'order' => 1,
                'siasn_id' => NULL,
                'id_tingkat' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'parent_id' => 2,
                'simpeg_id' => '1.1.',
                'hukuman' => 'Hukuman Disiplin Ringan',
                'jenis' => NULL,
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => NULL,
                'durasi_efek' => NULL,
                'proses' => NULL,
                'rentang' => NULL,
                'efek' => '0',
                'tingkat' => '0',
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:25:45',
                'order' => 1,
                'siasn_id' => NULL,
                'id_tingkat' => NULL,
            ),
            3 => 
            array (
                'id' => 7,
                'parent_id' => 2,
                'simpeg_id' => '1.2.',
                'hukuman' => 'Hukuman Disiplin Sedang',
                'jenis' => '1',
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => NULL,
                'durasi_efek' => NULL,
                'proses' => NULL,
                'rentang' => '1',
                'efek' => '0',
                'tingkat' => '2',
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:25:45',
                'order' => 1,
                'siasn_id' => NULL,
                'id_tingkat' => NULL,
            ),
            4 => 
            array (
                'id' => 25,
                'parent_id' => 24,
                'simpeg_id' => '4.1.',
                'hukuman' => 'Pemberhentian Sementara',
                'jenis' => '1',
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => '3',
                'durasi_efek' => NULL,
                'proses' => '3',
                'rentang' => '0',
                'efek' => '1',
                'tingkat' => '2',
                'keterangan' => NULL,
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:25:45',
                'order' => 1,
                'siasn_id' => NULL,
                'id_tingkat' => NULL,
            ),
            5 => 
            array (
                'id' => 26,
                'parent_id' => 24,
                'simpeg_id' => '4.2.',
                'hukuman' => 'Pencabutan Pemberhentian Sementara/Rehabilitasi',
                'jenis' => '1',
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => NULL,
                'durasi_efek' => NULL,
                'proses' => NULL,
                'rentang' => '1',
                'efek' => '0',
                'tingkat' => NULL,
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:25:45',
                'order' => 1,
                'siasn_id' => NULL,
                'id_tingkat' => NULL,
            ),
            6 => 
            array (
                'id' => 28,
                'parent_id' => 27,
                'simpeg_id' => '5.2.2.',
            'hukuman' => 'Penurunan Gaji Sebesar 1 kali Kenaikan Gaji Berkala untuk Paling Lama 1 (Satu) Tahun',
                'jenis' => '1',
                'jumlah_min' => '0',
                'jumlah_max' => NULL,
                'jenis_efek' => '0',
                'durasi_efek' => '0',
                'proses' => '0',
                'rentang' => '0',
                'efek' => '0',
                'tingkat' => '2',
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:26:35',
                'order' => 1,
                'siasn_id' => NULL,
                'id_tingkat' => NULL,
            ),
            7 => 
            array (
                'id' => 29,
                'parent_id' => 27,
                'simpeg_id' => '5.3.1.',
            'hukuman' => 'Penundaan Kenaikan Pangkat yang Setingkat Lebih Rendah untuk Paling Lama 1 (Satu) Tahun',
                'jenis' => '1',
                'jumlah_min' => '0',
                'jumlah_max' => NULL,
                'jenis_efek' => '0',
                'durasi_efek' => '0',
                'proses' => '0',
                'rentang' => '0',
                'efek' => '0',
                'tingkat' => '3',
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:26:35',
                'order' => 1,
                'siasn_id' => NULL,
                'id_tingkat' => NULL,
            ),
            8 => 
            array (
                'id' => 31,
                'parent_id' => 30,
                'simpeg_id' => '8.1.',
                'hukuman' => 'Skorsing',
                'jenis' => '1',
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => '4',
                'durasi_efek' => '1',
                'proses' => '3',
                'rentang' => '1',
                'efek' => '1',
                'tingkat' => NULL,
                'keterangan' => NULL,
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:25:45',
                'order' => 1,
                'siasn_id' => NULL,
                'id_tingkat' => NULL,
            ),
            9 => 
            array (
                'id' => 15,
                'parent_id' => NULL,
                'simpeg_id' => '10.',
                'hukuman' => 'Berdasarkan Peraturan Daerah',
                'jenis' => '0',
                'jumlah_min' => '0',
                'jumlah_max' => NULL,
                'jenis_efek' => '0',
                'durasi_efek' => '0',
                'proses' => '0',
                'rentang' => '0',
                'efek' => '0',
                'tingkat' => '0',
                'keterangan' => 'Berdasarkan Peraturan Daerah',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:26:35',
                'order' => 1,
                'siasn_id' => NULL,
                'id_tingkat' => NULL,
            ),
            10 => 
            array (
                'id' => 17,
                'parent_id' => NULL,
                'simpeg_id' => '11.',
                'hukuman' => 'Berdasarkan PP 94 Tahun 2021',
                'jenis' => NULL,
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => NULL,
                'durasi_efek' => NULL,
                'proses' => NULL,
                'rentang' => NULL,
                'efek' => '0',
                'tingkat' => NULL,
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:26:35',
                'order' => 1,
                'siasn_id' => NULL,
                'id_tingkat' => NULL,
            ),
            11 => 
            array (
                'id' => 18,
                'parent_id' => NULL,
                'simpeg_id' => '2.',
                'hukuman' => 'Berdasakan PP 32 Tahun 1979',
                'jenis' => NULL,
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => NULL,
                'durasi_efek' => NULL,
                'proses' => NULL,
                'rentang' => NULL,
                'efek' => '0',
                'tingkat' => NULL,
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:26:35',
                'order' => 1,
                'siasn_id' => NULL,
                'id_tingkat' => NULL,
            ),
            12 => 
            array (
                'id' => 23,
                'parent_id' => NULL,
                'simpeg_id' => '3.',
                'hukuman' => 'Berdasarkan PP 11 Tahun 2002',
                'jenis' => NULL,
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => NULL,
                'durasi_efek' => NULL,
                'proses' => NULL,
                'rentang' => NULL,
                'efek' => '0',
                'tingkat' => NULL,
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:26:35',
                'order' => 1,
                'siasn_id' => NULL,
                'id_tingkat' => NULL,
            ),
            13 => 
            array (
                'id' => 24,
                'parent_id' => NULL,
                'simpeg_id' => '4.',
                'hukuman' => 'Berdasarkan PP 4 Tahun 1966',
                'jenis' => NULL,
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => NULL,
                'durasi_efek' => NULL,
                'proses' => NULL,
                'rentang' => NULL,
                'efek' => '0',
                'tingkat' => NULL,
                'keterangan' => NULL,
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:26:35',
                'order' => 1,
                'siasn_id' => NULL,
                'id_tingkat' => NULL,
            ),
            14 => 
            array (
                'id' => 27,
                'parent_id' => NULL,
                'simpeg_id' => '5.',
                'hukuman' => 'Berdasarkan PP 30 Tahun 1980',
                'jenis' => NULL,
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => NULL,
                'durasi_efek' => NULL,
                'proses' => NULL,
                'rentang' => NULL,
                'efek' => '0',
                'tingkat' => NULL,
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:26:35',
                'order' => 1,
                'siasn_id' => NULL,
                'id_tingkat' => NULL,
            ),
            15 => 
            array (
                'id' => 2,
                'parent_id' => NULL,
                'simpeg_id' => '1.',
                'hukuman' => 'Berdasarkan PP 53 Tahun 2010',
                'jenis' => NULL,
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => NULL,
                'durasi_efek' => NULL,
                'proses' => NULL,
                'rentang' => NULL,
                'efek' => '0',
                'tingkat' => NULL,
                'keterangan' => ' ',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:26:35',
                'order' => 1,
                'siasn_id' => NULL,
                'id_tingkat' => NULL,
            ),
            16 => 
            array (
                'id' => 30,
                'parent_id' => NULL,
                'simpeg_id' => '8.',
                'hukuman' => 'Berdasarkan Pasal 88 UU ASN No. 8 Tahun 2014',
                'jenis' => NULL,
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => NULL,
                'durasi_efek' => NULL,
                'proses' => NULL,
                'rentang' => NULL,
                'efek' => '0',
                'tingkat' => '0',
                'keterangan' => NULL,
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:26:35',
                'order' => 1,
                'siasn_id' => NULL,
                'id_tingkat' => NULL,
            ),
            17 => 
            array (
                'id' => 11,
                'parent_id' => 2,
                'simpeg_id' => '1.3.',
                'hukuman' => 'Hukuman Disiplin Berat',
                'jenis' => '1',
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => NULL,
                'durasi_efek' => NULL,
                'proses' => NULL,
                'rentang' => '1',
                'efek' => '0',
                'tingkat' => '3',
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:25:45',
                'order' => 1,
                'siasn_id' => NULL,
                'id_tingkat' => NULL,
            ),
            18 => 
            array (
                'id' => 12,
                'parent_id' => 11,
                'simpeg_id' => '1.3.1.',
            'hukuman' => 'Penurunan Pangkat Setingkat Lebih Rendah Selama 3 (Tiga) Tahun',
                'jenis' => '1',
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => '1',
                'durasi_efek' => '5',
                'proses' => '1',
                'rentang' => '1',
                'efek' => '1',
                'tingkat' => '3',
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:26:35',
                'order' => 1,
                'siasn_id' => NULL,
                'id_tingkat' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'parent_id' => 18,
                'simpeg_id' => '2.2.',
                'hukuman' => 'Pemberhentian Tidak dengan Hormat sebagai CPNS',
                'jenis' => '1',
                'jumlah_min' => '0',
                'jumlah_max' => NULL,
                'jenis_efek' => '0',
                'durasi_efek' => '0',
                'proses' => '0',
                'rentang' => '0',
                'efek' => '0',
                'tingkat' => NULL,
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:25:45',
                'order' => 1,
                'siasn_id' => NULL,
                'id_tingkat' => NULL,
            ),
            20 => 
            array (
                'id' => 22,
                'parent_id' => 18,
                'simpeg_id' => '2.4.',
                'hukuman' => 'Pemberhentian dengan Hormat sebagai CPNS',
                'jenis' => '1',
                'jumlah_min' => '0',
                'jumlah_max' => NULL,
                'jenis_efek' => '0',
                'durasi_efek' => '0',
                'proses' => '0',
                'rentang' => '0',
                'efek' => '0',
                'tingkat' => NULL,
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:25:45',
                'order' => 1,
                'siasn_id' => NULL,
                'id_tingkat' => NULL,
            ),
            21 => 
            array (
                'id' => 19,
                'parent_id' => 18,
                'simpeg_id' => '2.1.',
                'hukuman' => 'Pemberhentian Tidak Dengan Hormat Sebagai PNS',
                'jenis' => '1',
                'jumlah_min' => '0',
                'jumlah_max' => NULL,
                'jenis_efek' => '0',
                'durasi_efek' => '0',
                'proses' => '0',
                'rentang' => '0',
                'efek' => '0',
                'tingkat' => NULL,
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:25:45',
                'order' => 1,
                'siasn_id' => '11',
                'id_tingkat' => 'B',
            ),
            22 => 
            array (
                'id' => 21,
                'parent_id' => 18,
                'simpeg_id' => '2.3.',
                'hukuman' => 'Pemberhentian Dengan Hormat Tidak Atas Permintaan Sendiri Sebagai PNS',
                'jenis' => '1',
                'jumlah_min' => '0',
                'jumlah_max' => NULL,
                'jenis_efek' => '0',
                'durasi_efek' => '0',
                'proses' => '0',
                'rentang' => '0',
                'efek' => '0',
                'tingkat' => NULL,
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:25:45',
                'order' => 1,
                'siasn_id' => '10',
                'id_tingkat' => 'B',
            ),
            23 => 
            array (
                'id' => 35,
                'parent_id' => NULL,
                'simpeg_id' => '12.1',
                'hukuman' => 'Sanksi Moral Terbuka',
                'jenis' => NULL,
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => NULL,
                'durasi_efek' => NULL,
                'proses' => NULL,
                'rentang' => NULL,
                'efek' => NULL,
                'tingkat' => NULL,
                'keterangan' => NULL,
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:26:35',
                'order' => 1,
                'siasn_id' => '21',
                'id_tingkat' => 'K',
            ),
            24 => 
            array (
                'id' => 36,
                'parent_id' => NULL,
                'simpeg_id' => '12.2',
                'hukuman' => 'Sanksi Moral Tertutup',
                'jenis' => NULL,
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => NULL,
                'durasi_efek' => NULL,
                'proses' => NULL,
                'rentang' => NULL,
                'efek' => NULL,
                'tingkat' => NULL,
                'keterangan' => NULL,
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:26:35',
                'order' => 1,
                'siasn_id' => '22',
                'id_tingkat' => 'K',
            ),
            25 => 
            array (
                'id' => 4,
                'parent_id' => 3,
                'simpeg_id' => '1.1.1.',
                'hukuman' => 'Teguran Lisan',
                'jenis' => NULL,
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => NULL,
                'durasi_efek' => NULL,
                'proses' => NULL,
                'rentang' => NULL,
                'efek' => '0',
                'tingkat' => '0',
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:26:35',
                'order' => 1,
                'siasn_id' => '01',
                'id_tingkat' => 'R',
            ),
            26 => 
            array (
                'id' => 5,
                'parent_id' => 3,
                'simpeg_id' => '1.1.2.',
                'hukuman' => 'Teguran Tertulis',
                'jenis' => '1',
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => NULL,
                'durasi_efek' => NULL,
                'proses' => NULL,
                'rentang' => '1',
                'efek' => '0',
                'tingkat' => '1',
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 06:24:06',
                'order' => 1,
                'siasn_id' => '02',
                'id_tingkat' => 'R',
            ),
            27 => 
            array (
                'id' => 6,
                'parent_id' => 3,
                'simpeg_id' => '1.1.3.',
                'hukuman' => 'Pernyataan Tidak Puas Secara Tertulis',
                'jenis' => '1',
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => NULL,
                'durasi_efek' => NULL,
                'proses' => NULL,
                'rentang' => '1',
                'efek' => '0',
                'tingkat' => '1',
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:26:35',
                'order' => 1,
                'siasn_id' => '03',
                'id_tingkat' => 'R',
            ),
            28 => 
            array (
                'id' => 8,
                'parent_id' => 7,
                'simpeg_id' => '1.2.1.',
            'hukuman' => 'Penundaan Kenaikan Gaji Berkala Selama 1 (Satu) Tahun',
                'jenis' => '1',
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => '1',
                'durasi_efek' => '1',
                'proses' => '2',
                'rentang' => '1',
                'efek' => '1',
                'tingkat' => '2',
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:26:35',
                'order' => 1,
                'siasn_id' => '04',
                'id_tingkat' => 'S',
            ),
            29 => 
            array (
                'id' => 9,
                'parent_id' => 7,
                'simpeg_id' => '1.2.2.',
            'hukuman' => 'Penundaan Kenaikan Pangkat Selama 1 (Satu) Tahun',
                'jenis' => '1',
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => '1',
                'durasi_efek' => '1',
                'proses' => '1',
                'rentang' => '1',
                'efek' => '1',
                'tingkat' => '2',
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:26:35',
                'order' => 1,
                'siasn_id' => '07',
                'id_tingkat' => 'S',
            ),
            30 => 
            array (
                'id' => 10,
                'parent_id' => 7,
                'simpeg_id' => '1.2.3.',
            'hukuman' => 'Penurunan Pangkat Setingkat Lebih Rendah Selama 1 (Satu) Tahun',
                'jenis' => '1',
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => '2',
                'durasi_efek' => '1',
                'proses' => '1',
                'rentang' => '1',
                'efek' => '1',
                'tingkat' => '2',
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:26:35',
                'order' => 1,
                'siasn_id' => '08',
                'id_tingkat' => 'S',
            ),
            31 => 
            array (
                'id' => 33,
                'parent_id' => 32,
                'simpeg_id' => '9.1.',
                'hukuman' => 'Pemberhentian Permanen',
                'jenis' => '0',
                'jumlah_min' => '0',
                'jumlah_max' => NULL,
                'jenis_efek' => '0',
                'durasi_efek' => '0',
                'proses' => '0',
                'rentang' => '0',
                'efek' => '0',
                'tingkat' => '0',
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:25:45',
                'order' => 1,
                'siasn_id' => NULL,
                'id_tingkat' => NULL,
            ),
            32 => 
            array (
                'id' => 34,
                'parent_id' => 32,
                'simpeg_id' => '9.2.',
                'hukuman' => 'Pelanggaran Kode Etik',
                'jenis' => NULL,
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => NULL,
                'durasi_efek' => NULL,
                'proses' => NULL,
                'rentang' => NULL,
                'efek' => NULL,
                'tingkat' => NULL,
                'keterangan' => NULL,
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:25:45',
                'order' => 1,
                'siasn_id' => NULL,
                'id_tingkat' => NULL,
            ),
            33 => 
            array (
                'id' => 13,
                'parent_id' => 11,
                'simpeg_id' => '1.3.2.',
            'hukuman' => 'Penurunan Jabatan Setingkat Lebih Rendah Selama 12 (Dua Belas) Bulan',
                'jenis' => '1',
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => '2',
                'durasi_efek' => '1',
                'proses' => '2',
                'rentang' => '1',
                'efek' => '1',
                'tingkat' => '3',
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:26:35',
                'order' => 1,
                'siasn_id' => '27',
                'id_tingkat' => 'B',
            ),
            34 => 
            array (
                'id' => 14,
                'parent_id' => 11,
                'simpeg_id' => '1.3.3.',
            'hukuman' => 'Pembebasan Dari Jabatannya Menjadi Jabatan Pelaksana Selama 12 (Dua Belas) Bulan',
                'jenis' => '1',
                'jumlah_min' => NULL,
                'jumlah_max' => NULL,
                'jenis_efek' => '4',
                'durasi_efek' => '2',
                'proses' => '3',
                'rentang' => '1',
                'efek' => '1',
                'tingkat' => '3',
                'keterangan' => '',
                'created_at' => '2023-07-01 04:51:28',
                'updated_at' => '2023-07-01 05:26:35',
                'order' => 1,
                'siasn_id' => '28',
                'id_tingkat' => 'B',
            ),
        ));
        
        
    }
}